create schema if not exists gold;
create schema if not exists semantic;

create table if not exists gold.dim_source (
  source_key bigint generated by default as identity primary key,
  source_code text not null,
  source_name text not null,
  source_type text not null default 'other',
  source_url text,
  reliability_classification text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_code)
);

create table if not exists gold.dim_unit (
  unit_key bigint generated by default as identity primary key,
  unit_code text not null,
  unit_name text not null,
  unit_symbol text,
  unit_category text not null default 'unknown',
  scale_factor numeric not null default 1,
  currency_code text,
  is_percentage boolean not null default false,
  is_index boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (unit_code)
);

create table if not exists gold.dim_date (
  date_key bigint generated by default as identity primary key,
  period_code text not null,
  period_type text not null,
  calendar_year integer,
  calendar_quarter integer,
  calendar_month integer,
  period_start_date date,
  period_end_date date,
  period_label text,
  is_complete_period boolean,
  source_period_value text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (period_code, period_type)
);

create table if not exists gold.dim_geography (
  geography_key bigint generated by default as identity primary key,
  geography_code text not null,
  geography_name text not null,
  geography_type text not null,
  geography_level_order integer,
  geography_level_label text,
  parent_geography_key bigint references gold.dim_geography(geography_key),
  municipality_code text,
  province_code text,
  country_code text,
  valid_from date not null default date '1900-01-01',
  valid_to date,
  is_current boolean not null default true,
  source_system text not null default 'unknown',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, geography_type, geography_code, valid_from)
);

create table if not exists gold.dim_dataset (
  dataset_key bigint generated by default as identity primary key,
  dataset_code text not null,
  dataset_title text not null,
  dataset_description text,
  source_organization text not null,
  source_system text not null,
  source_url text,
  dataset_version text not null,
  publication_date date,
  last_updated_at_source timestamptz,
  loaded_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, dataset_code, dataset_version)
);

create table if not exists gold.dim_measure (
  measure_key bigint generated by default as identity primary key,
  measure_code text not null,
  measure_name text not null,
  measure_description text,
  topic text,
  subtopic text,
  unit_key bigint not null references gold.dim_unit(unit_key),
  default_aggregation text not null default 'none',
  is_additive boolean not null default false,
  is_semi_additive boolean not null default false,
  is_non_additive boolean not null default true,
  value_type text not null default 'decimal',
  decimals integer,
  source_system text not null,
  dataset_code text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, dataset_code, measure_code)
);

create table if not exists gold.dim_category (
  category_key bigint generated by default as identity primary key,
  dataset_key bigint not null references gold.dim_dataset(dataset_key),
  dimension_code text not null,
  category_code text not null,
  category_name text not null,
  category_description text,
  parent_category_key bigint references gold.dim_category(category_key),
  category_level integer,
  sort_order integer,
  is_total boolean not null default false,
  is_unknown boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (dataset_key, dimension_code, category_code)
);

create table if not exists gold.fact_observation (
  observation_key bigint generated by default as identity primary key,
  dataset_key bigint not null references gold.dim_dataset(dataset_key),
  measure_key bigint not null references gold.dim_measure(measure_key),
  date_key bigint not null references gold.dim_date(date_key),
  geography_key bigint not null references gold.dim_geography(geography_key),
  source_key bigint not null references gold.dim_source(source_key),
  observation_value numeric,
  observation_text text,
  unit_key bigint not null references gold.dim_unit(unit_key),
  status_code text,
  is_missing boolean not null default false,
  is_suppressed boolean not null default false,
  is_preliminary boolean not null default false,
  source_observation_id text,
  silver_observation_id text,
  bronze_record_id text,
  ingestion_run_id uuid,
  category_combination_hash text not null,
  record_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (
    dataset_key,
    measure_key,
    date_key,
    geography_key,
    category_combination_hash,
    source_observation_id
  )
);

create table if not exists gold.bridge_observation_category (
  observation_key bigint not null references gold.fact_observation(observation_key) on delete cascade,
  category_key bigint not null references gold.dim_category(category_key),
  dimension_code text not null,
  created_at timestamptz not null default now(),
  primary key (observation_key, category_key)
);

create table if not exists gold.cbs_load_runs (
  run_id uuid primary key default gen_random_uuid(),
  dataset_code text,
  dataset_version text,
  status text not null default 'pending',
  source_observation_count bigint,
  gold_fact_count bigint,
  category_bridge_count bigint,
  missing_value_count bigint,
  suppressed_value_count bigint,
  preliminary_value_count bigint,
  unresolved_geography_count bigint,
  unknown_unit_count bigint,
  unmapped_measure_count bigint,
  validation_status text,
  validation_errors text[] not null default '{}',
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists gold.validation_result (
  validation_id uuid primary key default gen_random_uuid(),
  run_id uuid references gold.cbs_load_runs(run_id) on delete cascade,
  dataset_code text,
  check_name text not null,
  status text not null,
  expected_value text,
  actual_value text,
  message text,
  checked_at timestamptz not null default now()
);

create table if not exists semantic.metric (
  metric_id bigint generated by default as identity primary key,
  metric_name text not null unique,
  metric_label text not null,
  description text,
  measure_key bigint references gold.dim_measure(measure_key),
  aggregation text not null default 'none',
  unit_key bigint references gold.dim_unit(unit_key),
  default_time_dimension text not null default 'date_key',
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists semantic.metric_dimension (
  metric_id bigint not null references semantic.metric(metric_id) on delete cascade,
  dimension_name text not null,
  is_required boolean not null default false,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (metric_id, dimension_name)
);

create table if not exists semantic.synonym (
  synonym_id bigint generated by default as identity primary key,
  object_type text not null,
  object_id text not null,
  synonym text not null,
  language_code text not null default 'nl',
  created_at timestamptz not null default now(),
  unique (object_type, object_id, synonym, language_code)
);

create table if not exists semantic.caveat (
  caveat_id bigint generated by default as identity primary key,
  object_type text not null,
  object_id text not null,
  caveat_type text not null,
  description text not null,
  valid_from date,
  valid_to date,
  severity text,
  created_at timestamptz not null default now()
);

create table if not exists semantic.definition_version (
  definition_version_id bigint generated by default as identity primary key,
  object_type text not null,
  object_id text not null,
  definition_text text not null,
  valid_from date,
  valid_to date,
  comparability_status text,
  change_description text,
  created_at timestamptz not null default now()
);

insert into gold.dim_unit (
  unit_key, unit_code, unit_name, unit_symbol, unit_category, scale_factor, currency_code, is_percentage, is_index
) values
  (-1, 'UNKNOWN', 'Unknown unit', null, 'unknown', 1, null, false, false),
  (-2, 'COUNT', 'Count', null, 'count', 1, null, false, false),
  (-3, 'PERSONS', 'Persons', null, 'count', 1, null, false, false),
  (-4, 'HOUSEHOLDS', 'Households', null, 'count', 1, null, false, false),
  (-5, 'EUR', 'Euro', 'EUR', 'currency', 1, 'EUR', false, false),
  (-6, 'EUR_THOUSANDS', 'Thousand euro', 'EUR000', 'currency', 1000, 'EUR', false, false),
  (-10, 'EUR_MILLIONS', 'Million euro', 'EUR mln', 'currency', 1000000, 'EUR', false, false),
  (-7, 'PERCENT', 'Percent', '%', 'ratio', 1, null, true, false),
  (-8, 'PERCENTAGE_POINTS', 'Percentage points', 'pp', 'ratio', 1, null, false, false),
  (-9, 'INDEX', 'Index', null, 'index', 1, null, false, true),
  (-11, 'THOUSANDS', 'Thousands', '000', 'count', 1000, null, false, false),
  (-12, 'SQUARE_METERS', 'Square meters', 'm2', 'area', 1, null, false, false),
  (-13, 'CUBIC_METERS', 'Cubic meters', 'm3', 'volume', 1, null, false, false),
  (-14, 'HOURS', 'Hours', 'h', 'time', 1, null, false, false)
on conflict (unit_code) do update set
  unit_name = excluded.unit_name,
  unit_symbol = excluded.unit_symbol,
  unit_category = excluded.unit_category,
  scale_factor = excluded.scale_factor,
  currency_code = excluded.currency_code,
  is_percentage = excluded.is_percentage,
  is_index = excluded.is_index,
  updated_at = now();

insert into gold.dim_source (
  source_key, source_code, source_name, source_type, source_url, reliability_classification
) values
  (-1, 'UNKNOWN', 'Unknown source', 'other', null, null),
  (-2, 'CBS', 'Centraal Bureau voor de Statistiek', 'government', 'https://www.cbs.nl', null)
on conflict (source_code) do update set
  source_name = excluded.source_name,
  source_type = excluded.source_type,
  source_url = excluded.source_url,
  updated_at = now();

insert into gold.dim_date (
  date_key, period_code, period_type, calendar_year, period_label, is_complete_period, source_period_value
) values
  (-1, 'UNKNOWN', 'unknown', null, 'Unknown period', null, 'UNKNOWN')
on conflict (period_code, period_type) do update set
  period_label = excluded.period_label,
  updated_at = now();

alter table gold.dim_geography add column if not exists geography_level_order integer;
alter table gold.dim_geography add column if not exists geography_level_label text;

insert into gold.dim_geography (
  geography_key, geography_code, geography_name, geography_type, geography_level_order, geography_level_label, country_code, source_system
) values
  (-1, 'UNKNOWN', 'Nederland', 'country', 5, 'Totaal (Nederland)', 'NL', 'UNKNOWN')
on conflict (geography_key) do update set
  geography_code = excluded.geography_code,
  geography_name = excluded.geography_name,
  geography_type = excluded.geography_type,
  geography_level_order = excluded.geography_level_order,
  geography_level_label = excluded.geography_level_label,
  country_code = excluded.country_code,
  source_system = excluded.source_system,
  updated_at = now();

update gold.dim_geography
set geography_type = case
    when geography_code in ('UNKNOWN', 'NL', 'NL00', 'NL01') then 'country'
    when upper(geography_code) like 'CR%' or upper(geography_code) like 'COROP%' then 'corop'
    when upper(geography_code) like 'LD%' then 'landsdeel'
    else geography_type
  end,
  geography_name = case
    when geography_code = 'UNKNOWN' then 'Nederland'
    else geography_name
  end,
  country_code = coalesce(country_code, 'NL'),
  geography_level_order = case
    when upper(geography_code) like 'GM%' then 1
    when upper(geography_code) like 'CR%' or upper(geography_code) like 'COROP%' then 2
    when upper(geography_code) like 'PV%' then 3
    when upper(geography_code) like 'LD%' then 4
    when geography_code in ('UNKNOWN', 'NL', 'NL00', 'NL01') then 5
    else geography_level_order
  end,
  geography_level_label = case
    when upper(geography_code) like 'GM%' then 'Gemeente'
    when upper(geography_code) like 'CR%' or upper(geography_code) like 'COROP%' then 'COROP-gebied'
    when upper(geography_code) like 'PV%' then 'Provincie'
    when upper(geography_code) like 'LD%' then 'Landsdeel'
    when geography_code in ('UNKNOWN', 'NL', 'NL00', 'NL01') then 'Totaal (Nederland)'
    else geography_level_label
  end,
  updated_at = now()
where geography_type in ('region', 'unknown')
   or upper(geography_code) like 'GM%'
   or upper(geography_code) like 'CR%'
   or upper(geography_code) like 'COROP%'
   or upper(geography_code) like 'PV%'
   or upper(geography_code) like 'LD%'
   or geography_code in ('UNKNOWN', 'NL', 'NL00', 'NL01');

create or replace function gold.canonical_geography_type(
  p_geography_code text,
  p_geography_type text default null
)
returns text
language sql
immutable
as $$
  select case
    when upper(coalesce(nullif(p_geography_code, ''), 'UNKNOWN')) in ('UNKNOWN', 'NL', 'NL00', 'NL01') then 'country'
    when upper(coalesce(p_geography_code, '')) like 'GM%' then 'municipality'
    when upper(coalesce(p_geography_code, '')) like 'WK%' or upper(coalesce(p_geography_code, '')) like 'BU%' then 'neighborhood'
    when upper(coalesce(p_geography_code, '')) like 'CR%' or upper(coalesce(p_geography_code, '')) like 'COROP%' then 'corop'
    when upper(coalesce(p_geography_code, '')) like 'PV%' then 'province'
    when upper(coalesce(p_geography_code, '')) like 'LD%' then 'landsdeel'
    when lower(coalesce(nullif(p_geography_type, ''), 'unknown')) in ('country', 'national', 'totaal') then 'country'
    when lower(coalesce(nullif(p_geography_type, ''), 'unknown')) = 'region' then 'region'
    when lower(coalesce(nullif(p_geography_type, ''), 'unknown')) = 'unknown' then 'country'
    else lower(p_geography_type)
  end
$$;

create or replace function gold.geography_level_order(p_geography_type text)
returns integer
language sql
immutable
as $$
  select case lower(coalesce(nullif(p_geography_type, ''), 'country'))
    when 'municipality' then 1
    when 'neighborhood' then 0
    when 'corop' then 2
    when 'region' then 2
    when 'province' then 3
    when 'landsdeel' then 4
    when 'country' then 5
    when 'national' then 5
    when 'totaal' then 5
    when 'unknown' then 5
    else 99
  end
$$;

create or replace function gold.geography_level_label(p_geography_type text)
returns text
language sql
immutable
as $$
  select case lower(coalesce(nullif(p_geography_type, ''), 'country'))
    when 'municipality' then 'Gemeente'
    when 'neighborhood' then 'Wijk/buurt'
    when 'corop' then 'COROP-gebied'
    when 'region' then 'Regionaal'
    when 'province' then 'Provincie'
    when 'landsdeel' then 'Landsdeel'
    when 'country' then 'Totaal (Nederland)'
    when 'national' then 'Totaal (Nederland)'
    when 'totaal' then 'Totaal (Nederland)'
    when 'unknown' then 'Totaal (Nederland)'
    else p_geography_type
  end
$$;

create index if not exists fact_observation_dataset_idx on gold.fact_observation(dataset_key);
create index if not exists fact_observation_measure_idx on gold.fact_observation(measure_key);
create index if not exists fact_observation_date_idx on gold.fact_observation(date_key);
create index if not exists fact_observation_geography_idx on gold.fact_observation(geography_key);
create index if not exists fact_observation_measure_date_idx on gold.fact_observation(measure_key, date_key);
create index if not exists fact_observation_measure_geography_date_idx on gold.fact_observation(measure_key, geography_key, date_key);
create index if not exists fact_observation_dataset_measure_date_idx on gold.fact_observation(dataset_key, measure_key, date_key);
create index if not exists bridge_observation_category_category_idx on gold.bridge_observation_category(category_key, observation_key);
create index if not exists bridge_observation_category_observation_idx on gold.bridge_observation_category(observation_key);
create index if not exists dim_geography_code_idx on gold.dim_geography(geography_code);
create index if not exists dim_measure_code_idx on gold.dim_measure(measure_code);
create index if not exists dim_dataset_code_idx on gold.dim_dataset(dataset_code);
create index if not exists dim_category_dataset_dimension_code_idx on gold.dim_category(dataset_key, dimension_code, category_code);
create index if not exists semantic_metric_measure_idx on semantic.metric(measure_key);
create index if not exists semantic_synonym_lookup_idx on semantic.synonym(object_type, synonym, language_code);

alter table gold.dim_source enable row level security;
alter table gold.dim_unit enable row level security;
alter table gold.dim_date enable row level security;
alter table gold.dim_geography enable row level security;
alter table gold.dim_dataset enable row level security;
alter table gold.dim_measure enable row level security;
alter table gold.dim_category enable row level security;
alter table gold.fact_observation enable row level security;
alter table gold.bridge_observation_category enable row level security;
alter table gold.cbs_load_runs enable row level security;
alter table gold.validation_result enable row level security;
alter table semantic.metric enable row level security;
alter table semantic.metric_dimension enable row level security;
alter table semantic.synonym enable row level security;
alter table semantic.caveat enable row level security;
alter table semantic.definition_version enable row level security;

drop policy if exists "gold_dim_source_read_public" on gold.dim_source;
create policy "gold_dim_source_read_public" on gold.dim_source for select using (true);
drop policy if exists "gold_dim_unit_read_public" on gold.dim_unit;
create policy "gold_dim_unit_read_public" on gold.dim_unit for select using (true);
drop policy if exists "gold_dim_date_read_public" on gold.dim_date;
create policy "gold_dim_date_read_public" on gold.dim_date for select using (true);
drop policy if exists "gold_dim_geography_read_public" on gold.dim_geography;
create policy "gold_dim_geography_read_public" on gold.dim_geography for select using (true);
drop policy if exists "gold_dim_dataset_read_public" on gold.dim_dataset;
create policy "gold_dim_dataset_read_public" on gold.dim_dataset for select using (true);
drop policy if exists "gold_dim_measure_read_public" on gold.dim_measure;
create policy "gold_dim_measure_read_public" on gold.dim_measure for select using (true);
drop policy if exists "gold_dim_category_read_public" on gold.dim_category;
create policy "gold_dim_category_read_public" on gold.dim_category for select using (true);
drop policy if exists "gold_fact_observation_read_public" on gold.fact_observation;
create policy "gold_fact_observation_read_public" on gold.fact_observation for select using (true);
drop policy if exists "gold_bridge_observation_category_read_public" on gold.bridge_observation_category;
create policy "gold_bridge_observation_category_read_public" on gold.bridge_observation_category for select using (true);
drop policy if exists "semantic_metric_read_public" on semantic.metric;
create policy "semantic_metric_read_public" on semantic.metric for select using (true);
drop policy if exists "semantic_metric_dimension_read_public" on semantic.metric_dimension;
create policy "semantic_metric_dimension_read_public" on semantic.metric_dimension for select using (true);
drop policy if exists "semantic_synonym_read_public" on semantic.synonym;
create policy "semantic_synonym_read_public" on semantic.synonym for select using (true);
drop policy if exists "semantic_caveat_read_public" on semantic.caveat;
create policy "semantic_caveat_read_public" on semantic.caveat for select using (true);
drop policy if exists "semantic_definition_version_read_public" on semantic.definition_version;
create policy "semantic_definition_version_read_public" on semantic.definition_version for select using (true);
