create schema if not exists gold_bouwen_wonen;

create table if not exists gold_bouwen_wonen.dim_housing_dataset (
  housing_dataset_key bigint primary key,
  dataset_key bigint not null references gold.dim_dataset(dataset_key),
  dataset_code text not null,
  dataset_title text not null,
  dataset_version text not null,
  source_system text not null,
  source_url text,
  source_organization text,
  last_updated_at_source timestamptz,
  domain_id text not null default 'bouwen-en-wonen',
  domain_name text not null default 'Bouwen en wonen',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (dataset_key)
);

create table if not exists gold_bouwen_wonen.dim_housing_indicator (
  housing_indicator_key bigint primary key,
  measure_key bigint not null references gold.dim_measure(measure_key),
  dataset_key bigint not null references gold.dim_dataset(dataset_key),
  measure_code text not null,
  indicator_name text not null,
  indicator_description text,
  topic text,
  subtopic text,
  unit_key bigint not null references gold.dim_unit(unit_key),
  unit_code text,
  unit_name text,
  default_aggregation text not null,
  is_additive boolean not null,
  is_non_additive boolean not null,
  value_type text not null,
  modelling_status text not null default 'source-mapped',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (measure_key)
);

create table if not exists gold_bouwen_wonen.fact_housing_observation (
  housing_observation_key bigint generated by default as identity primary key,
  observation_key bigint,
  housing_dataset_key bigint not null references gold_bouwen_wonen.dim_housing_dataset(housing_dataset_key),
  housing_indicator_key bigint not null references gold_bouwen_wonen.dim_housing_indicator(housing_indicator_key),
  dataset_key bigint not null references gold.dim_dataset(dataset_key),
  measure_key bigint not null references gold.dim_measure(measure_key),
  date_key bigint not null references gold.dim_date(date_key),
  geography_key bigint not null references gold.dim_geography(geography_key),
  unit_key bigint not null references gold.dim_unit(unit_key),
  calendar_year integer,
  period_code text,
  period_type text,
  geography_code text,
  geography_name text,
  geography_type text,
  municipality_code text,
  province_code text,
  country_code text,
  observation_value numeric,
  observation_text text,
  status_code text,
  is_missing boolean not null default false,
  is_suppressed boolean not null default false,
  category_combination_hash text not null,
  source_observation_id text,
  silver_observation_id text,
  bronze_record_id text,
  record_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (observation_key)
);

do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select c.conname
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    join pg_class rt on rt.oid = c.confrelid
    join pg_namespace rn on rn.oid = rt.relnamespace
    where n.nspname = 'gold_bouwen_wonen'
      and t.relname = 'fact_housing_observation'
      and c.contype = 'f'
      and rn.nspname = 'gold'
      and rt.relname = 'fact_observation'
  loop
    execute format('alter table gold_bouwen_wonen.fact_housing_observation drop constraint if exists %I', constraint_name);
  end loop;
end $$;

alter table gold_bouwen_wonen.fact_housing_observation
  alter column observation_key drop not null,
  add column if not exists dataset_code text,
  add column if not exists measure_code text,
  add column if not exists source_dataset_id text,
  add column if not exists source_row_id text,
  add column if not exists bronze_ingestion_run_id uuid;

create table if not exists gold_bouwen_wonen.bridge_housing_observation_category (
  housing_observation_key bigint not null references gold_bouwen_wonen.fact_housing_observation(housing_observation_key) on delete cascade,
  category_key bigint not null references gold.dim_category(category_key),
  dimension_code text not null,
  category_code text,
  category_name text,
  created_at timestamptz not null default now(),
  primary key (housing_observation_key, category_key)
);

create table if not exists gold_bouwen_wonen.load_runs (
  run_id uuid primary key default gen_random_uuid(),
  status text not null default 'pending',
  source_fact_count bigint,
  mart_fact_count bigint,
  bridge_row_count bigint,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  message text
);

create index if not exists fact_housing_observation_dataset_idx
  on gold_bouwen_wonen.fact_housing_observation(housing_dataset_key);

create index if not exists fact_housing_observation_dataset_source_row_idx
  on gold_bouwen_wonen.fact_housing_observation(housing_dataset_key, source_row_id);

create index if not exists fact_housing_observation_source_dataset_idx
  on gold_bouwen_wonen.fact_housing_observation(source_dataset_id);

create index if not exists fact_housing_observation_indicator_idx
  on gold_bouwen_wonen.fact_housing_observation(housing_indicator_key);

create index if not exists fact_housing_observation_year_geography_idx
  on gold_bouwen_wonen.fact_housing_observation(calendar_year, geography_type, geography_code);

create index if not exists fact_housing_observation_geo_indicator_date_idx
  on gold_bouwen_wonen.fact_housing_observation(geography_key, housing_indicator_key, date_key);

create index if not exists fact_housing_observation_measure_year_geo_name_idx
  on gold_bouwen_wonen.fact_housing_observation(measure_key, calendar_year, lower(geography_name))
  where observation_value is not null and is_missing = false;

create index if not exists fact_housing_observation_measure_year_value_idx
  on gold_bouwen_wonen.fact_housing_observation(measure_key, calendar_year, observation_value desc)
  where observation_value is not null and is_missing = false;

create unique index if not exists fact_housing_observation_source_grain_uidx
  on gold_bouwen_wonen.fact_housing_observation(
    dataset_key,
    measure_key,
    date_key,
    geography_key,
    category_combination_hash,
    source_observation_id
  );

create index if not exists bridge_housing_observation_category_category_idx
  on gold_bouwen_wonen.bridge_housing_observation_category(category_key, housing_observation_key);

alter table gold_bouwen_wonen.dim_housing_dataset enable row level security;
alter table gold_bouwen_wonen.dim_housing_indicator enable row level security;
alter table gold_bouwen_wonen.fact_housing_observation enable row level security;
alter table gold_bouwen_wonen.bridge_housing_observation_category enable row level security;
alter table gold_bouwen_wonen.load_runs enable row level security;

drop policy if exists "gold_bouwen_wonen_dataset_read_public" on gold_bouwen_wonen.dim_housing_dataset;
create policy "gold_bouwen_wonen_dataset_read_public"
  on gold_bouwen_wonen.dim_housing_dataset for select
  using (true);

drop policy if exists "gold_bouwen_wonen_indicator_read_public" on gold_bouwen_wonen.dim_housing_indicator;
create policy "gold_bouwen_wonen_indicator_read_public"
  on gold_bouwen_wonen.dim_housing_indicator for select
  using (true);

drop policy if exists "gold_bouwen_wonen_fact_read_public" on gold_bouwen_wonen.fact_housing_observation;
create policy "gold_bouwen_wonen_fact_read_public"
  on gold_bouwen_wonen.fact_housing_observation for select
  using (true);

drop policy if exists "gold_bouwen_wonen_bridge_read_public" on gold_bouwen_wonen.bridge_housing_observation_category;
create policy "gold_bouwen_wonen_bridge_read_public"
  on gold_bouwen_wonen.bridge_housing_observation_category for select
  using (true);
