create schema if not exists semantic;

create table if not exists semantic.gold_capability_run (
  capability_run_id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  mart_filter text,
  domain_filter text,
  dataset_filter text,
  dataset_count integer not null default 0,
  measure_count integer not null default 0,
  grain_count integer not null default 0,
  error_message text
);

create table if not exists semantic.gold_dataset_capability (
  capability_id bigint generated by default as identity primary key,
  domain_id text not null,
  mart_schema text not null,
  fact_table text not null,
  dataset_key bigint not null,
  dataset_code text not null,
  dataset_title text,
  source_system text,
  source_organization text,
  source_url text,
  source_last_updated_at timestamptz,
  gold_loaded_at timestamptz,
  loaded_fact_rows bigint not null default 0,
  populated_fact_rows bigint not null default 0,
  missing_fact_rows bigint not null default 0,
  measure_count integer not null default 0,
  geography_count integer not null default 0,
  category_dimension_count integer not null default 0,
  category_value_count integer not null default 0,
  min_year integer,
  max_year integer,
  available_years integer[] not null default '{}',
  period_types text[] not null default '{}',
  geography_types text[] not null default '{}',
  grains text[] not null default '{}',
  supports_national_year boolean not null default false,
  supports_province_year boolean not null default false,
  supports_region_year boolean not null default false,
  supports_municipality_year boolean not null default false,
  supports_trend boolean not null default false,
  supports_ranking boolean not null default false,
  supports_comparison boolean not null default false,
  capability_status text not null default 'unknown',
  capability_notes text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  last_profiled_at timestamptz not null default now(),
  capability_run_id uuid references semantic.gold_capability_run(capability_run_id),
  unique (domain_id, mart_schema, fact_table, dataset_code)
);

create table if not exists semantic.gold_measure_capability (
  capability_id bigint generated by default as identity primary key,
  domain_id text not null,
  mart_schema text not null,
  fact_table text not null,
  dataset_code text not null,
  measure_key bigint not null,
  measure_code text,
  measure_name text,
  measure_description text,
  unit_code text,
  unit_name text,
  unit_category text,
  scale_factor numeric,
  default_aggregation text,
  value_type text,
  is_additive boolean,
  is_non_additive boolean,
  loaded_fact_rows bigint not null default 0,
  populated_fact_rows bigint not null default 0,
  min_year integer,
  max_year integer,
  available_years integer[] not null default '{}',
  period_types text[] not null default '{}',
  geography_types text[] not null default '{}',
  grains text[] not null default '{}',
  supports_national_year boolean not null default false,
  supports_province_year boolean not null default false,
  supports_region_year boolean not null default false,
  supports_municipality_year boolean not null default false,
  supports_trend boolean not null default false,
  supports_ranking boolean not null default false,
  supports_comparison boolean not null default false,
  executable_candidate boolean not null default false,
  non_executable_reasons text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  last_profiled_at timestamptz not null default now(),
  capability_run_id uuid references semantic.gold_capability_run(capability_run_id),
  unique (domain_id, mart_schema, fact_table, dataset_code, measure_key)
);

create table if not exists semantic.gold_grain_capability (
  capability_id bigint generated by default as identity primary key,
  domain_id text not null,
  mart_schema text not null,
  fact_table text not null,
  dataset_code text not null,
  measure_key bigint not null,
  geography_type text not null,
  period_type text not null,
  grain text not null,
  loaded_fact_rows bigint not null default 0,
  populated_fact_rows bigint not null default 0,
  geography_count integer not null default 0,
  category_combination_count integer not null default 0,
  min_year integer,
  max_year integer,
  available_years integer[] not null default '{}',
  last_profiled_at timestamptz not null default now(),
  capability_run_id uuid references semantic.gold_capability_run(capability_run_id),
  unique (domain_id, mart_schema, fact_table, dataset_code, measure_key, geography_type, period_type)
);

create table if not exists semantic.semantic_evaluation_suite (
  evaluation_suite_id bigint generated by default as identity primary key,
  suite_code text not null unique,
  suite_name text not null,
  description text,
  domain_id text,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists semantic.semantic_evaluation_case (
  evaluation_case_id bigint generated by default as identity primary key,
  suite_code text not null references semantic.semantic_evaluation_suite(suite_code) on delete cascade,
  case_code text not null unique,
  question text not null,
  language_code text not null default 'nl',
  domain_id text not null,
  expected_intent text not null,
  expected_metric_code text,
  expected_dataset_code text,
  expected_source text,
  expected_geography_type text,
  expected_grain text,
  expected_year integer,
  expected_year_start integer,
  expected_year_end integer,
  expected_category_filters jsonb not null default '{}'::jsonb,
  expected_component_metrics jsonb not null default '[]'::jsonb,
  should_execute boolean not null default true,
  minimum_rows integer not null default 1,
  expected_no_execute_reason text,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists semantic.semantic_evaluation_run (
  evaluation_run_id uuid primary key default gen_random_uuid(),
  suite_code text,
  domain_id text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  total_cases integer not null default 0,
  passed_cases integer not null default 0,
  failed_cases integer not null default 0,
  skipped_cases integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  error_message text
);

create table if not exists semantic.semantic_evaluation_result (
  evaluation_result_id bigint generated by default as identity primary key,
  evaluation_run_id uuid not null references semantic.semantic_evaluation_run(evaluation_run_id) on delete cascade,
  evaluation_case_id bigint references semantic.semantic_evaluation_case(evaluation_case_id) on delete set null,
  case_code text not null,
  question text not null,
  status text not null,
  checks jsonb not null default '{}'::jsonb,
  query_plan jsonb not null default '{}'::jsonb,
  availability_result jsonb not null default '{}'::jsonb,
  execution_result jsonb not null default '{}'::jsonb,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists gold_dataset_capability_domain_idx
  on semantic.gold_dataset_capability(domain_id, capability_status, dataset_code);

create index if not exists gold_measure_capability_lookup_idx
  on semantic.gold_measure_capability(domain_id, dataset_code, measure_key);

create index if not exists gold_measure_capability_grains_idx
  on semantic.gold_measure_capability using gin(grains);

create index if not exists gold_grain_capability_lookup_idx
  on semantic.gold_grain_capability(domain_id, dataset_code, grain, measure_key);

create index if not exists semantic_evaluation_case_suite_idx
  on semantic.semantic_evaluation_case(suite_code, domain_id, is_active);

alter table if exists semantic.semantic_evaluation_case
  add column if not exists expected_component_metrics jsonb not null default '[]'::jsonb;

create index if not exists semantic_evaluation_result_run_idx
  on semantic.semantic_evaluation_result(evaluation_run_id, status);

alter table semantic.gold_capability_run enable row level security;
alter table semantic.gold_dataset_capability enable row level security;
alter table semantic.gold_measure_capability enable row level security;
alter table semantic.gold_grain_capability enable row level security;
alter table semantic.semantic_evaluation_suite enable row level security;
alter table semantic.semantic_evaluation_case enable row level security;
alter table semantic.semantic_evaluation_run enable row level security;
alter table semantic.semantic_evaluation_result enable row level security;

drop policy if exists "semantic_gold_capability_run_read_public" on semantic.gold_capability_run;
create policy "semantic_gold_capability_run_read_public" on semantic.gold_capability_run for select using (true);

drop policy if exists "semantic_gold_dataset_capability_read_public" on semantic.gold_dataset_capability;
create policy "semantic_gold_dataset_capability_read_public" on semantic.gold_dataset_capability for select using (true);

drop policy if exists "semantic_gold_measure_capability_read_public" on semantic.gold_measure_capability;
create policy "semantic_gold_measure_capability_read_public" on semantic.gold_measure_capability for select using (true);

drop policy if exists "semantic_gold_grain_capability_read_public" on semantic.gold_grain_capability;
create policy "semantic_gold_grain_capability_read_public" on semantic.gold_grain_capability for select using (true);

drop policy if exists "semantic_evaluation_suite_read_public" on semantic.semantic_evaluation_suite;
create policy "semantic_evaluation_suite_read_public" on semantic.semantic_evaluation_suite for select using (is_active);

drop policy if exists "semantic_evaluation_case_read_public" on semantic.semantic_evaluation_case;
create policy "semantic_evaluation_case_read_public" on semantic.semantic_evaluation_case for select using (is_active);

drop policy if exists "semantic_evaluation_run_read_public" on semantic.semantic_evaluation_run;
create policy "semantic_evaluation_run_read_public" on semantic.semantic_evaluation_run for select using (true);

drop policy if exists "semantic_evaluation_result_read_public" on semantic.semantic_evaluation_result;
create policy "semantic_evaluation_result_read_public" on semantic.semantic_evaluation_result for select using (true);
