create schema if not exists semantic;

create table if not exists semantic.metric_alias (
  metric_alias_id bigint generated by default as identity primary key,
  alias text not null,
  normalized_alias text not null,
  language_code text not null default 'nl',
  domain_id text not null default '',
  measure_key bigint,
  dataset_code text,
  priority integer not null default 100,
  metadata_origin text not null default 'curated',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_alias, language_code, domain_id, measure_key)
);

create table if not exists semantic.metric_preference (
  metric_preference_id bigint generated by default as identity primary key,
  preference_code text not null unique,
  normalized_metric_label text not null,
  domain_id text,
  geography_type text,
  calculation_code text,
  preferred_measure_key bigint not null,
  preferred_dataset_code text,
  priority integer not null default 100,
  reason text,
  metadata_origin text not null default 'curated',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists semantic.metric_grain (
  metric_grain_id bigint generated by default as identity primary key,
  measure_key bigint not null,
  dataset_code text,
  geography_type text not null,
  period_type text not null default '',
  min_year integer,
  max_year integer,
  fact_row_count bigint not null default 0,
  is_supported boolean not null default true,
  metadata_origin text not null default 'generated',
  updated_at timestamptz not null default now(),
  unique (measure_key, geography_type, period_type)
);

create table if not exists semantic.geography_alias (
  geography_alias_id bigint generated by default as identity primary key,
  alias text not null,
  normalized_alias text not null,
  language_code text not null default 'nl',
  geography_type text not null,
  geography_name text not null,
  geography_code text,
  priority integer not null default 100,
  metadata_origin text not null default 'curated',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_alias, language_code, geography_type, geography_name)
);

create table if not exists semantic.golden_question (
  golden_question_id bigint generated by default as identity primary key,
  question text not null unique,
  domain_id text not null default 'bouwen-en-wonen',
  expected_intent text not null,
  expected_calculation_code text,
  expected_metric_code text,
  expected_dataset_code text,
  expected_measure_label text,
  expected_secondary_measure_label text,
  expected_geography_names text[] not null default '{}',
  expected_geography_type text,
  expected_grain text,
  expected_category_filters jsonb not null default '{}'::jsonb,
  expected_year integer,
  expected_year_start integer,
  expected_year_end integer,
  expected_result_shape jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  metadata_origin text not null default 'curated',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists semantic.golden_question
  add column if not exists expected_metric_code text,
  add column if not exists expected_dataset_code text,
  add column if not exists expected_grain text,
  add column if not exists expected_category_filters jsonb not null default '{}'::jsonb;

create table if not exists semantic.metric_contract (
  metric_contract_id bigint generated by default as identity primary key,
  metric_code text not null unique,
  label text not null,
  description text,
  domain_id text not null default 'bouwen-en-wonen',
  measure_key bigint not null,
  dataset_codes text[] not null default '{}',
  unit_code text,
  aggregation text not null default 'none',
  valid_grains text[] not null default '{}',
  default_grain text,
  synonyms jsonb not null default '{}'::jsonb,
  exclusions text[] not null default '{}',
  supports jsonb not null default '{}'::jsonb,
  category_filters jsonb not null default '{}'::jsonb,
  selection_priority integer not null default 100,
  metadata_origin text not null default 'generated',
  contract_status text not null default 'generated',
  execution_status text not null default 'disabled',
  semantic_quality_status text not null default 'incomplete',
  availability_status text not null default 'unknown',
  availability_checked_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists semantic.metric_contract
  add column if not exists contract_status text not null default 'generated',
  add column if not exists execution_status text not null default 'disabled',
  add column if not exists semantic_quality_status text not null default 'incomplete',
  add column if not exists availability_status text not null default 'unknown',
  add column if not exists availability_checked_at timestamptz;

create table if not exists semantic.concept (
  concept_id bigint generated by default as identity primary key,
  concept_code text not null unique,
  label text not null,
  description text,
  domain_id text not null default 'bouwen-en-wonen',
  language_code text not null default 'nl',
  synonyms jsonb not null default '{}'::jsonb,
  exclusions text[] not null default '{}',
  required_unit_code text,
  default_grain text,
  valid_grains text[] not null default '{}',
  supported_operations text[] not null default '{}',
  ambiguity_policy text not null default 'ask',
  metadata_origin text not null default 'curated',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists semantic.concept_metric_binding (
  concept_metric_binding_id bigint generated by default as identity primary key,
  concept_code text not null references semantic.concept(concept_code) on delete cascade,
  metric_code text not null references semantic.metric_contract(metric_code) on delete cascade,
  measure_key bigint not null,
  dataset_code text not null,
  binding_role text not null default 'primary',
  priority integer not null default 100,
  required_unit_code text,
  allowed_grains text[] not null default '{}',
  category_filters jsonb not null default '{}'::jsonb,
  union_rule_code text,
  selection_reason text,
  is_active boolean not null default true,
  metadata_origin text not null default 'curated',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (concept_code, metric_code, binding_role)
);

create table if not exists semantic.dimension_contract (
  dimension_contract_id bigint generated by default as identity primary key,
  dimension_code text not null,
  dataset_code text,
  domain_id text not null default 'bouwen-en-wonen',
  label text not null,
  description text,
  dimension_role text not null default 'category',
  canonical_total_value text,
  valid_values jsonb not null default '[]'::jsonb,
  value_synonyms jsonb not null default '{}'::jsonb,
  resolution_rules jsonb not null default '{}'::jsonb,
  supports_grouping boolean not null default true,
  supports_filtering boolean not null default true,
  metadata_origin text not null default 'generated',
  contract_status text not null default 'generated',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (domain_id, dataset_code, dimension_code)
);

create table if not exists semantic.category_value_contract (
  category_value_contract_id bigint generated by default as identity primary key,
  contract_code text not null unique,
  domain_id text not null default 'bouwen-en-wonen',
  dataset_code text not null,
  metric_code text not null,
  measure_key bigint not null,
  measure_name text,
  unit_code text,
  aggregation text not null default 'sum',
  dimension_code text not null,
  category_code text,
  category_name text not null,
  label text not null,
  description text,
  synonyms jsonb not null default '{}'::jsonb,
  category_filters jsonb not null default '{}'::jsonb,
  valid_grains text[] not null default '{}',
  default_grain text,
  supports jsonb not null default '{"ranking": true, "comparison": true, "trend": true, "percentage_change": true}'::jsonb,
  is_total boolean not null default false,
  is_unknown boolean not null default false,
  selection_priority integer not null default 60,
  metadata_origin text not null default 'generated',
  contract_status text not null default 'profiled',
  execution_status text not null default 'enabled',
  semantic_quality_status text not null default 'category_value_profiled',
  availability_status text not null default 'unknown',
  availability_checked_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (dataset_code, measure_key, dimension_code, category_code)
);

create table if not exists semantic.contract_availability (
  contract_availability_id bigint generated by default as identity primary key,
  metric_code text not null,
  dataset_code text not null,
  measure_key bigint not null,
  geography_type text not null,
  period_type text not null default 'year',
  calendar_year integer,
  category_filter_hash text not null default 'none',
  category_filters jsonb not null default '{}'::jsonb,
  row_count bigint not null default 0,
  geography_count bigint not null default 0,
  min_value numeric,
  max_value numeric,
  availability_status text not null default 'available',
  metadata_origin text not null default 'generated',
  checked_at timestamptz not null default now(),
  unique (metric_code, dataset_code, measure_key, geography_type, period_type, calendar_year, category_filter_hash)
);

create index if not exists semantic_metric_alias_lookup_idx
  on semantic.metric_alias(normalized_alias, language_code, domain_id, priority);

create index if not exists semantic_metric_preference_lookup_idx
  on semantic.metric_preference(normalized_metric_label, domain_id, geography_type, calculation_code, priority)
  where is_active;

create index if not exists semantic_metric_grain_lookup_idx
  on semantic.metric_grain(measure_key, geography_type, period_type);

create index if not exists semantic_geography_alias_lookup_idx
  on semantic.geography_alias(normalized_alias, geography_type, priority);

create index if not exists semantic_metric_contract_measure_idx
  on semantic.metric_contract(measure_key);

create index if not exists semantic_metric_contract_domain_idx
  on semantic.metric_contract(domain_id, is_active, selection_priority);

create index if not exists semantic_metric_contract_execution_idx
  on semantic.metric_contract(domain_id, execution_status, contract_status, is_active, selection_priority);

create index if not exists semantic_concept_domain_idx
  on semantic.concept(domain_id, is_active, concept_code);

create index if not exists semantic_concept_metric_binding_lookup_idx
  on semantic.concept_metric_binding(concept_code, binding_role, priority)
  where is_active;

create index if not exists semantic_dimension_contract_lookup_idx
  on semantic.dimension_contract(domain_id, dataset_code, dimension_code)
  where is_active;

create index if not exists semantic_category_value_contract_lookup_idx
  on semantic.category_value_contract(domain_id, dataset_code, dimension_code, category_name)
  where is_active;

create index if not exists semantic_category_value_contract_metric_idx
  on semantic.category_value_contract(metric_code, dataset_code, measure_key)
  where is_active;

create index if not exists semantic_contract_availability_lookup_idx
  on semantic.contract_availability(metric_code, dataset_code, geography_type, calendar_year, category_filter_hash);

create index if not exists semantic_contract_availability_measure_idx
  on semantic.contract_availability(measure_key, dataset_code, geography_type, calendar_year);

alter table semantic.metric_alias enable row level security;
alter table semantic.metric_preference enable row level security;
alter table semantic.metric_grain enable row level security;
alter table semantic.geography_alias enable row level security;
alter table semantic.golden_question enable row level security;
alter table semantic.metric_contract enable row level security;
alter table semantic.concept enable row level security;
alter table semantic.concept_metric_binding enable row level security;
alter table semantic.dimension_contract enable row level security;
alter table semantic.category_value_contract enable row level security;
alter table semantic.contract_availability enable row level security;

drop policy if exists "semantic_metric_alias_read_public" on semantic.metric_alias;
create policy "semantic_metric_alias_read_public" on semantic.metric_alias for select using (true);

drop policy if exists "semantic_metric_preference_read_public" on semantic.metric_preference;
create policy "semantic_metric_preference_read_public" on semantic.metric_preference for select using (is_active);

drop policy if exists "semantic_metric_grain_read_public" on semantic.metric_grain;
create policy "semantic_metric_grain_read_public" on semantic.metric_grain for select using (true);

drop policy if exists "semantic_geography_alias_read_public" on semantic.geography_alias;
create policy "semantic_geography_alias_read_public" on semantic.geography_alias for select using (true);

drop policy if exists "semantic_golden_question_read_public" on semantic.golden_question;
create policy "semantic_golden_question_read_public" on semantic.golden_question for select using (is_active);

drop policy if exists "semantic_metric_contract_read_public" on semantic.metric_contract;
create policy "semantic_metric_contract_read_public" on semantic.metric_contract for select using (is_active);

drop policy if exists "semantic_concept_read_public" on semantic.concept;
create policy "semantic_concept_read_public" on semantic.concept for select using (is_active);

drop policy if exists "semantic_concept_metric_binding_read_public" on semantic.concept_metric_binding;
create policy "semantic_concept_metric_binding_read_public" on semantic.concept_metric_binding for select using (is_active);

drop policy if exists "semantic_dimension_contract_read_public" on semantic.dimension_contract;
create policy "semantic_dimension_contract_read_public" on semantic.dimension_contract for select using (is_active);

drop policy if exists "semantic_category_value_contract_read_public" on semantic.category_value_contract;
create policy "semantic_category_value_contract_read_public" on semantic.category_value_contract for select using (is_active);

drop policy if exists "semantic_contract_availability_read_public" on semantic.contract_availability;
create policy "semantic_contract_availability_read_public" on semantic.contract_availability for select using (true);
