create extension if not exists vector;
create extension if not exists pgcrypto;

create schema if not exists semantic;

create table if not exists semantic.metric (
  metric_id bigint generated by default as identity primary key,
  metric_name text not null unique,
  metric_label text not null,
  description text,
  measure_key bigint references gold.dim_measure(measure_key),
  aggregation text not null default 'none',
  unit_key bigint references gold.dim_unit(unit_key),
  default_time_dimension text not null default 'date_key',
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists semantic.metric_dimension (
  metric_id bigint not null references semantic.metric(metric_id) on delete cascade,
  dimension_name text not null,
  is_required boolean not null default false,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (metric_id, dimension_name)
);

create table if not exists semantic.synonym (
  synonym_id bigint generated by default as identity primary key,
  object_type text not null,
  object_id text not null,
  synonym text not null,
  language_code text not null default 'nl',
  created_at timestamptz not null default now(),
  unique (object_type, object_id, synonym, language_code)
);

create table if not exists semantic.caveat (
  caveat_id bigint generated by default as identity primary key,
  object_type text not null,
  object_id text not null,
  caveat_type text not null,
  description text not null,
  valid_from date,
  valid_to date,
  severity text,
  created_at timestamptz not null default now()
);

create table if not exists semantic.definition_version (
  definition_version_id bigint generated by default as identity primary key,
  object_type text not null,
  object_id text not null,
  definition_text text not null,
  valid_from date,
  valid_to date,
  comparability_status text,
  change_description text,
  created_at timestamptz not null default now()
);

alter table if exists semantic.metric add column if not exists metric_code text;
alter table if exists semantic.metric add column if not exists dataset_key bigint;
alter table if exists semantic.metric add column if not exists value_type text;
alter table if exists semantic.metric add column if not exists default_geography_level text;
alter table if exists semantic.metric add column if not exists is_additive boolean default false;
alter table if exists semantic.metric add column if not exists is_semi_additive boolean default false;
alter table if exists semantic.metric add column if not exists is_non_additive boolean default true;
alter table if exists semantic.metric add column if not exists supports_time_comparison boolean default true;
alter table if exists semantic.metric add column if not exists supports_geography_comparison boolean default true;
alter table if exists semantic.metric add column if not exists metadata_completeness_status text default 'incomplete';
alter table if exists semantic.metric add column if not exists metadata_origin text not null default 'generated';

create unique index if not exists semantic_metric_code_uidx
  on semantic.metric(metric_code)
  where metric_code is not null;

create index if not exists semantic_metric_measure_idx
  on semantic.metric(measure_key);

create table if not exists semantic.dimension (
  dimension_id bigint generated by default as identity primary key,
  dimension_code text not null,
  dimension_name text not null,
  dimension_label text not null,
  description text,
  dimension_type text not null,
  physical_table text,
  physical_key_column text,
  physical_label_column text,
  hierarchy_name text,
  is_filterable boolean not null default true,
  is_groupable boolean not null default true,
  is_enabled boolean not null default true,
  metadata_origin text not null default 'generated',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (dimension_code)
);

alter table if exists semantic.dimension
  add column if not exists metadata_origin text not null default 'generated';

alter table if exists semantic.metric_dimension
  add column if not exists dimension_id bigint references semantic.dimension(dimension_id),
  add column if not exists supports_grouping boolean not null default true,
  add column if not exists supports_filtering boolean not null default true,
  add column if not exists metadata_origin text not null default 'generated';

create unique index if not exists semantic_metric_dimension_id_uidx
  on semantic.metric_dimension(metric_id, dimension_id)
  where dimension_id is not null;

alter table if exists semantic.synonym
  add column if not exists normalized_synonym text,
  add column if not exists weight numeric not null default 1,
  add column if not exists metadata_origin text not null default 'source';

create index if not exists semantic_synonym_normalized_idx
  on semantic.synonym(object_type, normalized_synonym, language_code);

create table if not exists semantic.calculation (
  calculation_id bigint generated by default as identity primary key,
  calculation_code text not null,
  calculation_name text not null,
  description text,
  calculation_type text not null,
  required_period_count integer,
  supports_ranking boolean not null default false,
  supports_grouping boolean not null default false,
  is_enabled boolean not null default true,
  metadata_origin text not null default 'generated',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (calculation_code)
);

alter table if exists semantic.calculation
  add column if not exists metadata_origin text not null default 'generated';

create table if not exists semantic.join_path (
  join_path_id bigint generated by default as identity primary key,
  from_object text not null,
  from_column text not null,
  to_object text not null,
  to_column text not null,
  join_type text not null default 'inner',
  relationship_cardinality text not null,
  is_enabled boolean not null default true,
  metadata_origin text not null default 'generated',
  created_at timestamptz not null default now(),
  unique (from_object, from_column, to_object, to_column)
);

alter table if exists semantic.join_path
  add column if not exists metadata_origin text not null default 'generated';

alter table if exists semantic.caveat
  add column if not exists source_reference text,
  add column if not exists metadata_origin text not null default 'source';

alter table if exists semantic.definition_version
  add column if not exists source_reference text,
  add column if not exists metadata_origin text not null default 'source';

create table if not exists semantic.query_example (
  query_example_id bigint generated by default as identity primary key,
  metric_id bigint references semantic.metric(metric_id) on delete cascade,
  question text not null,
  language_code text not null default 'nl',
  intent_type text not null,
  expected_calculation_code text references semantic.calculation(calculation_code),
  expected_dimensions jsonb not null default '[]'::jsonb,
  metadata_origin text not null default 'generated',
  created_at timestamptz not null default now(),
  unique (metric_id, question, language_code)
);

alter table if exists semantic.query_example
  add column if not exists metadata_origin text not null default 'generated';

create table if not exists semantic.catalogue_item (
  catalogue_item_id uuid primary key default gen_random_uuid(),
  object_type text not null,
  object_id text not null,
  source_schema text,
  source_table text,
  source_pk text,
  title text not null,
  subtitle text,
  description text,
  search_text text not null,
  language_code text not null default 'nl',
  provider text,
  dataset_code text,
  measure_code text,
  geography_code text,
  unit_code text,
  domain_id text,
  tags text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  search_vector tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(subtitle, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(description, '')), 'C') ||
    setweight(to_tsvector('simple', coalesce(search_text, '')), 'D')
  ) stored,
  embedding vector(64),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (object_type, object_id)
);

create table if not exists semantic.search_telemetry (
  search_id uuid primary key default gen_random_uuid(),
  query_text text not null,
  classified_intent text,
  resolved_plan jsonb,
  result_count integer,
  latency_ms integer,
  created_at timestamptz not null default now()
);

create table if not exists semantic.answer_provenance (
  answer_id uuid primary key default gen_random_uuid(),
  question text not null,
  intent text not null,
  query_plan jsonb not null,
  compiled_sql_fingerprint text,
  result_summary jsonb not null default '{}'::jsonb,
  sources jsonb not null default '[]'::jsonb,
  confidence numeric,
  created_at timestamptz not null default now()
);

create table if not exists semantic.saved_analysis (
  analysis_id uuid primary key default gen_random_uuid(),
  answer_id uuid references semantic.answer_provenance(answer_id) on delete set null,
  title text not null,
  question text not null,
  summary text,
  query_plan jsonb not null default '{}'::jsonb,
  sources jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists semantic.evidence_conversion (
  evidence_id uuid primary key default gen_random_uuid(),
  answer_id uuid references semantic.answer_provenance(answer_id) on delete cascade,
  evidence_status text not null default 'candidate',
  title text not null,
  claim text,
  sources jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists semantic.answer_feedback (
  feedback_id uuid primary key default gen_random_uuid(),
  answer_id uuid references semantic.answer_provenance(answer_id) on delete cascade,
  rating text not null,
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists semantic.analytical_query_run (
  query_run_id uuid primary key default gen_random_uuid(),
  question text not null,
  query_plan jsonb not null,
  compiled_sql_fingerprint text,
  selected_metric_id text,
  selected_dimensions text[] not null default '{}',
  expected_columns jsonb not null default '[]'::jsonb,
  row_count integer,
  duration_ms integer,
  validation_status text not null,
  warnings jsonb not null default '[]'::jsonb,
  errors jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists semantic.golden_question (
  golden_question_id bigint generated by default as identity primary key,
  question text not null unique,
  domain_id text not null default 'bouwen-en-wonen',
  expected_intent text not null,
  expected_calculation_code text,
  expected_metric_code text,
  expected_dataset_code text,
  expected_measure_label text,
  expected_secondary_measure_label text,
  expected_geography_names text[] not null default '{}',
  expected_geography_type text,
  expected_grain text,
  expected_category_filters jsonb not null default '{}'::jsonb,
  expected_year integer,
  expected_year_start integer,
  expected_year_end integer,
  expected_result_shape jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  metadata_origin text not null default 'curated',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists semantic.golden_question
  add column if not exists expected_metric_code text,
  add column if not exists expected_dataset_code text,
  add column if not exists expected_grain text,
  add column if not exists expected_category_filters jsonb not null default '{}'::jsonb;

create table if not exists semantic.dimension_contract (
  dimension_contract_id bigint generated by default as identity primary key,
  dimension_code text not null,
  dataset_code text,
  domain_id text not null default 'bouwen-en-wonen',
  label text not null,
  description text,
  dimension_role text not null default 'category',
  canonical_total_value text,
  valid_values jsonb not null default '[]'::jsonb,
  value_synonyms jsonb not null default '{}'::jsonb,
  resolution_rules jsonb not null default '{}'::jsonb,
  supports_grouping boolean not null default true,
  supports_filtering boolean not null default true,
  metadata_origin text not null default 'generated',
  contract_status text not null default 'generated',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (domain_id, dataset_code, dimension_code)
);

create table if not exists semantic.category_value_contract (
  category_value_contract_id bigint generated by default as identity primary key,
  contract_code text not null unique,
  domain_id text not null default 'bouwen-en-wonen',
  dataset_code text not null,
  metric_code text not null,
  measure_key bigint not null,
  measure_name text,
  unit_code text,
  aggregation text not null default 'sum',
  dimension_code text not null,
  category_code text,
  category_name text not null,
  label text not null,
  description text,
  synonyms jsonb not null default '{}'::jsonb,
  category_filters jsonb not null default '{}'::jsonb,
  valid_grains text[] not null default '{}',
  default_grain text,
  supports jsonb not null default '{"ranking": true, "comparison": true, "trend": true, "percentage_change": true}'::jsonb,
  is_total boolean not null default false,
  is_unknown boolean not null default false,
  selection_priority integer not null default 60,
  metadata_origin text not null default 'generated',
  contract_status text not null default 'profiled',
  execution_status text not null default 'enabled',
  semantic_quality_status text not null default 'category_value_profiled',
  availability_status text not null default 'unknown',
  availability_checked_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (dataset_code, measure_key, dimension_code, category_code)
);

create table if not exists semantic.contract_availability (
  contract_availability_id bigint generated by default as identity primary key,
  metric_code text not null,
  dataset_code text not null,
  measure_key bigint not null,
  geography_type text not null,
  period_type text not null default 'year',
  calendar_year integer,
  category_filter_hash text not null default 'none',
  category_filters jsonb not null default '{}'::jsonb,
  row_count bigint not null default 0,
  geography_count bigint not null default 0,
  min_value numeric,
  max_value numeric,
  availability_status text not null default 'available',
  metadata_origin text not null default 'generated',
  checked_at timestamptz not null default now(),
  unique (metric_code, dataset_code, measure_key, geography_type, period_type, calendar_year, category_filter_hash)
);

insert into semantic.dimension (
  dimension_code, dimension_name, dimension_label, description, dimension_type,
  physical_table, physical_key_column, physical_label_column, hierarchy_name, is_filterable, is_groupable
) values
  ('time', 'Time', 'Time', 'CBS Perioden values standardized in gold.dim_date.', 'time', 'gold.dim_date', 'date_key', 'period_label', 'calendar', true, true),
  ('geography', 'Geography', 'Geography', 'CBS regional entities standardized in gold.dim_geography.', 'geography', 'gold.dim_geography', 'geography_key', 'geography_name', 'country-province-municipality-neighborhood', true, true),
  ('category', 'Category', 'Category', 'CBS categorical dimensions standardized in gold.dim_category.', 'category', 'gold.dim_category', 'category_key', 'category_name', null, true, true),
  ('dataset', 'Dataset', 'Dataset', 'Source dataset metadata from gold.dim_dataset.', 'dataset', 'gold.dim_dataset', 'dataset_key', 'dataset_title', null, true, true),
  ('source', 'Source', 'Source', 'Provider and provenance metadata from gold.dim_source.', 'source', 'gold.dim_source', 'source_key', 'source_name', null, true, false),
  ('status', 'Status', 'Status', 'Observation status flags such as missing, suppressed or preliminary.', 'status', null, 'status_code', 'status_code', null, true, true)
on conflict (dimension_code) do update set
  dimension_name = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.dimension_name else excluded.dimension_name end,
  dimension_label = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.dimension_label else excluded.dimension_label end,
  description = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.description else excluded.description end,
  dimension_type = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.dimension_type else excluded.dimension_type end,
  physical_table = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.physical_table else excluded.physical_table end,
  physical_key_column = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.physical_key_column else excluded.physical_key_column end,
  physical_label_column = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.physical_label_column else excluded.physical_label_column end,
  hierarchy_name = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.hierarchy_name else excluded.hierarchy_name end,
  is_filterable = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.is_filterable else excluded.is_filterable end,
  is_groupable = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.is_groupable else excluded.is_groupable end,
  is_enabled = case when semantic.dimension.metadata_origin = 'curated' then semantic.dimension.is_enabled else true end,
  updated_at = now();

insert into semantic.calculation (
  calculation_code, calculation_name, description, calculation_type, required_period_count, supports_ranking, supports_grouping
) values
  ('lookup', 'Lookup', 'Return the definition or direct value for a resolved object.', 'lookup', null, false, false),
  ('ranking', 'Ranking', 'Rank dimension values by a metric value.', 'ranking', null, true, true),
  ('trend', 'Trend', 'Show a metric over time.', 'time_series', 2, false, true),
  ('comparison', 'Comparison', 'Compare selected dimension values for one metric.', 'comparison', null, false, true),
  ('absolute_change', 'Absolute change', 'Calculate value difference between two periods.', 'change', 2, false, true),
  ('percentage_change', 'Percentage change', 'Calculate percentage difference between two periods.', 'change', 2, false, true),
  ('share_of_total', 'Share of total', 'Calculate a part as share of a total.', 'share', null, false, true),
  ('metric_comparison', 'Metric comparison', 'Compare multiple metrics for the same geography and period.', 'comparison', null, false, true),
  ('multi_metric_rank', 'Multi-metric ranking', 'Rank geographies by two metrics with deterministic rank directions.', 'ranking', null, true, true),
  ('change_rank', 'Change ranking', 'Rank geographies by absolute value change between two periods.', 'change', 2, true, true),
  ('compare_to_average', 'Compare to average', 'Compare selected geographies with the average across comparable geographies.', 'comparison', null, false, true),
  ('category_breakdown', 'Category breakdown', 'Break a metric down by a trusted categorical dimension.', 'breakdown', null, false, true),
  ('count', 'Count', 'Count records or entities where counting is valid.', 'count', null, true, true)
on conflict (calculation_code) do update set
  calculation_name = case when semantic.calculation.metadata_origin = 'curated' then semantic.calculation.calculation_name else excluded.calculation_name end,
  description = case when semantic.calculation.metadata_origin = 'curated' then semantic.calculation.description else excluded.description end,
  calculation_type = case when semantic.calculation.metadata_origin = 'curated' then semantic.calculation.calculation_type else excluded.calculation_type end,
  required_period_count = case when semantic.calculation.metadata_origin = 'curated' then semantic.calculation.required_period_count else excluded.required_period_count end,
  supports_ranking = case when semantic.calculation.metadata_origin = 'curated' then semantic.calculation.supports_ranking else excluded.supports_ranking end,
  supports_grouping = case when semantic.calculation.metadata_origin = 'curated' then semantic.calculation.supports_grouping else excluded.supports_grouping end,
  is_enabled = case when semantic.calculation.metadata_origin = 'curated' then semantic.calculation.is_enabled else true end,
  updated_at = now();

insert into semantic.join_path (
  from_object, from_column, to_object, to_column, join_type, relationship_cardinality
) values
  ('gold_bouwen_wonen.fact_housing_observation', 'dataset_key', 'gold.dim_dataset', 'dataset_key', 'inner', 'many_to_one'),
  ('gold_bouwen_wonen.fact_housing_observation', 'measure_key', 'gold.dim_measure', 'measure_key', 'inner', 'many_to_one'),
  ('gold_bouwen_wonen.fact_housing_observation', 'date_key', 'gold.dim_date', 'date_key', 'inner', 'many_to_one'),
  ('gold_bouwen_wonen.fact_housing_observation', 'geography_key', 'gold.dim_geography', 'geography_key', 'inner', 'many_to_one'),
  ('gold_bouwen_wonen.fact_housing_observation', 'unit_key', 'gold.dim_unit', 'unit_key', 'inner', 'many_to_one'),
  ('gold_bouwen_wonen.bridge_housing_observation_category', 'housing_observation_key', 'gold_bouwen_wonen.fact_housing_observation', 'housing_observation_key', 'inner', 'many_to_one'),
  ('gold_bouwen_wonen.bridge_housing_observation_category', 'category_key', 'gold.dim_category', 'category_key', 'inner', 'many_to_one')
on conflict (from_object, from_column, to_object, to_column) do update set
  join_type = case when semantic.join_path.metadata_origin = 'curated' then semantic.join_path.join_type else excluded.join_type end,
  relationship_cardinality = case when semantic.join_path.metadata_origin = 'curated' then semantic.join_path.relationship_cardinality else excluded.relationship_cardinality end,
  is_enabled = case when semantic.join_path.metadata_origin = 'curated' then semantic.join_path.is_enabled else true end;

create index if not exists semantic_catalogue_item_search_idx
  on semantic.catalogue_item using gin (search_vector);

create index if not exists semantic_catalogue_item_embedding_idx
  on semantic.catalogue_item using ivfflat (embedding vector_cosine_ops)
  with (lists = 64);

create index if not exists semantic_catalogue_item_type_idx
  on semantic.catalogue_item(object_type);

create index if not exists semantic_catalogue_item_dataset_idx
  on semantic.catalogue_item(dataset_code);

create index if not exists semantic_catalogue_item_domain_idx
  on semantic.catalogue_item(domain_id);

create index if not exists semantic_dimension_contract_lookup_idx
  on semantic.dimension_contract(domain_id, dataset_code, dimension_code)
  where is_active;

create index if not exists semantic_category_value_contract_lookup_idx
  on semantic.category_value_contract(domain_id, dataset_code, dimension_code, category_name)
  where is_active;

create index if not exists semantic_category_value_contract_metric_idx
  on semantic.category_value_contract(metric_code, dataset_code, measure_key)
  where is_active;

create index if not exists semantic_contract_availability_lookup_idx
  on semantic.contract_availability(metric_code, dataset_code, geography_type, calendar_year, category_filter_hash);

create index if not exists semantic_contract_availability_measure_idx
  on semantic.contract_availability(measure_key, dataset_code, geography_type, calendar_year);

create table if not exists semantic.metric_contract_observation (
  metric_code text not null,
  housing_observation_key bigint not null,
  dataset_code text not null,
  measure_key bigint not null,
  category_filter_hash text not null,
  metadata_origin text not null default 'generated',
  indexed_at timestamptz not null default now(),
  primary key (metric_code, housing_observation_key)
);

create index if not exists semantic_metric_contract_observation_lookup_idx
  on semantic.metric_contract_observation(metric_code, measure_key, dataset_code, housing_observation_key);

alter table semantic.dimension enable row level security;
alter table semantic.calculation enable row level security;
alter table semantic.join_path enable row level security;
alter table semantic.query_example enable row level security;
alter table semantic.catalogue_item enable row level security;
alter table semantic.search_telemetry enable row level security;
alter table semantic.answer_provenance enable row level security;
alter table semantic.saved_analysis enable row level security;
alter table semantic.evidence_conversion enable row level security;
alter table semantic.answer_feedback enable row level security;
alter table semantic.analytical_query_run enable row level security;
alter table semantic.golden_question enable row level security;
alter table semantic.dimension_contract enable row level security;
alter table semantic.category_value_contract enable row level security;
alter table semantic.contract_availability enable row level security;

drop policy if exists "semantic_dimension_read_public" on semantic.dimension;
create policy "semantic_dimension_read_public"
  on semantic.dimension for select
  using (is_enabled);

drop policy if exists "semantic_calculation_read_public" on semantic.calculation;
create policy "semantic_calculation_read_public"
  on semantic.calculation for select
  using (is_enabled);

drop policy if exists "semantic_join_path_read_public" on semantic.join_path;
create policy "semantic_join_path_read_public"
  on semantic.join_path for select
  using (is_enabled);

drop policy if exists "semantic_query_example_read_public" on semantic.query_example;
create policy "semantic_query_example_read_public"
  on semantic.query_example for select
  using (true);

drop policy if exists "semantic_catalogue_item_read_public" on semantic.catalogue_item;
create policy "semantic_catalogue_item_read_public"
  on semantic.catalogue_item for select
  using (is_active);

drop policy if exists "semantic_answer_provenance_read_public" on semantic.answer_provenance;
create policy "semantic_answer_provenance_read_public"
  on semantic.answer_provenance for select
  using (true);

drop policy if exists "semantic_saved_analysis_read_public" on semantic.saved_analysis;
create policy "semantic_saved_analysis_read_public"
  on semantic.saved_analysis for select
  using (true);

drop policy if exists "semantic_analytical_query_run_read_public" on semantic.analytical_query_run;
create policy "semantic_analytical_query_run_read_public"
  on semantic.analytical_query_run for select
  using (true);

drop policy if exists "semantic_golden_question_read_public" on semantic.golden_question;
create policy "semantic_golden_question_read_public"
  on semantic.golden_question for select
  using (is_active);

drop policy if exists "semantic_dimension_contract_read_public" on semantic.dimension_contract;
create policy "semantic_dimension_contract_read_public"
  on semantic.dimension_contract for select
  using (is_active);

drop policy if exists "semantic_category_value_contract_read_public" on semantic.category_value_contract;
create policy "semantic_category_value_contract_read_public"
  on semantic.category_value_contract for select
  using (is_active);

drop policy if exists "semantic_contract_availability_read_public" on semantic.contract_availability;
create policy "semantic_contract_availability_read_public"
  on semantic.contract_availability for select
  using (true);

drop function if exists public.guara_hybrid_search(text, text, integer, text[]);
create or replace function public.guara_hybrid_search(
  search_query text,
  query_embedding text default null,
  match_count integer default 10,
  object_types text[] default null
)
returns table (
  catalogue_item_id uuid,
  object_type text,
  object_id text,
  title text,
  subtitle text,
  description text,
  dataset_code text,
  measure_code text,
  geography_code text,
  unit_code text,
  domain_id text,
  provider text,
  rank_score numeric,
  lexical_score numeric,
  vector_score numeric,
  metadata jsonb
)
language sql
stable
security definer
set search_path = public, semantic, gold, gold_bouwen_wonen
as $$
  with q as (
    select
      websearch_to_tsquery('simple', coalesce(search_query, '')) as tsq,
      array(
        select token
        from regexp_split_to_table(lower(coalesce(search_query, '')), '[^[:alnum:]]+') as token
        where length(token) >= 3
      ) as tokens,
      case
        when nullif(query_embedding, '') is null then null
        else query_embedding::vector(64)
      end as embedding
  ),
  scored as (
    select
      c.catalogue_item_id,
      c.object_type,
      c.object_id,
      c.title,
      c.subtitle,
      c.description,
      c.dataset_code,
      c.measure_code,
      c.geography_code,
      c.unit_code,
      c.domain_id,
      c.provider,
      (
        case when q.tsq @@ c.search_vector then ts_rank_cd(c.search_vector, q.tsq) else 0 end
        +
        case
          when exists (
            select 1 from unnest(q.tokens) token
            where lower(c.search_text) like '%' || token || '%'
               or lower(c.title) like '%' || token || '%'
          ) then 0.05
          else 0
        end
      ) as lexical_score,
      case
        when q.embedding is not null and c.embedding is not null then 1 - (c.embedding <=> q.embedding)
        else 0
      end as vector_score,
      c.metadata
    from semantic.catalogue_item c
    cross join q
    where c.is_active
      and (object_types is null or c.object_type = any(object_types))
      and (
        q.tsq @@ c.search_vector
        or q.embedding is not null
        or exists (
          select 1 from unnest(q.tokens) token
          where lower(c.search_text) like '%' || token || '%'
             or lower(c.title) like '%' || token || '%'
        )
      )
  )
  select
    scored.catalogue_item_id,
    scored.object_type,
    scored.object_id,
    scored.title,
    scored.subtitle,
    scored.description,
    scored.dataset_code,
    scored.measure_code,
    scored.geography_code,
    scored.unit_code,
    scored.domain_id,
    scored.provider,
    round(((scored.lexical_score * 0.65) + (scored.vector_score * 0.35))::numeric, 6) as rank_score,
    round(scored.lexical_score::numeric, 6) as lexical_score,
    round(scored.vector_score::numeric, 6) as vector_score,
    scored.metadata
  from scored
  order by ((scored.lexical_score * 0.65) + (scored.vector_score * 0.35)) desc, scored.title asc
  limit greatest(1, least(coalesce(match_count, 10), 50));
$$;

create or replace function semantic.guara_observation_matches_metric_filters(plan jsonb, observation_key bigint)
returns boolean
language plpgsql
stable
security definer
set search_path = semantic, gold_bouwen_wonen, public
as $$
declare
  metric_code_filter text := nullif(plan->>'metric_code', '');
begin
  if coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
     or coalesce(plan->'category_filters', '{}'::jsonb) = '{}'::jsonb then
    return true;
  end if;

  if metric_code_filter is not null and exists (
    select 1
    from semantic.metric_contract_observation mco
    where mco.metric_code = metric_code_filter
  ) then
    return exists (
      select 1
      from semantic.metric_contract_observation mco
      where mco.metric_code = metric_code_filter
        and mco.housing_observation_key = observation_key
    );
  end if;

  return not exists (
    select 1
    from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
    where not exists (
      select 1
      from gold_bouwen_wonen.bridge_housing_observation_category required_category
      where required_category.housing_observation_key = observation_key
        and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
        and (
          required_category.category_name = required_filter.category_value
          or required_category.category_code = required_filter.category_value
        )
    )
  );
end;
$$;

drop function if exists public.guara_execute_query_plan(jsonb);
create or replace function public.guara_execute_query_plan(plan jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, gold, gold_bouwen_wonen, semantic
as $$
declare
  intent text := coalesce(plan->>'intent', '');
  measure bigint := nullif(plan->>'measure_key', '')::bigint;
  secondary_measure bigint := nullif(plan->>'secondary_measure_key', '')::bigint;
  metric_row record;
  resolved_calculation_code text;
  year_value integer := nullif(plan->>'year', '')::integer;
  year_start_value integer := nullif(plan->>'year_start', '')::integer;
  year_end_value integer := nullif(plan->>'year_end', '')::integer;
  geography_type_filter text := coalesce(nullif(plan->>'geography_type', ''), case when intent = 'rank_geographies' then 'municipality' else null end);
  sort_direction text := case when lower(coalesce(plan->>'sort_direction', 'desc')) = 'asc' then 'asc' else 'desc' end;
  value_filter_operator text := lower(coalesce(plan->>'value_filter_operator', ''));
  value_filter_value numeric := nullif(plan->>'value_filter', '')::numeric;
  limit_value integer := greatest(1, least(coalesce(nullif(plan->>'limit', '')::integer, 10), 50));
  result jsonb;
begin
  if intent not in ('rank_geographies', 'compare_geographies', 'trend', 'lookup_measure') then
    raise exception 'Unsupported query intent: %', intent;
  end if;

  resolved_calculation_code := coalesce(
    nullif(plan->>'calculation_code', ''),
    case intent
      when 'rank_geographies' then 'ranking'
      when 'compare_geographies' then 'comparison'
      when 'trend' then 'trend'
      when 'lookup_measure' then 'lookup'
      else null
    end
  );

  if not exists (
    select 1
    from semantic.calculation
    where calculation_code = resolved_calculation_code
      and is_enabled
  ) then
    raise exception 'Calculation is not approved or enabled: %', resolved_calculation_code;
  end if;

  if intent = 'lookup_measure' then
    if measure is not null and not exists (
      select 1
      from semantic.metric
      where measure_key = measure
        and is_enabled
    ) then
      raise exception 'Measure is not enabled in semantic.metric.';
    end if;

    select jsonb_build_object(
      'columns', jsonb_build_array('measure_key', 'measure_code', 'measure_name', 'unit_code', 'unit_name', 'scale_factor', 'default_aggregation', 'value_type', 'dataset_code'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      select
        m.measure_key::text as measure_key,
        m.measure_code,
        m.measure_name,
        u.unit_code,
        u.unit_name,
        u.scale_factor,
        sm.aggregation as default_aggregation,
        m.value_type,
        m.dataset_code
      from semantic.metric sm
      join gold.dim_measure m on m.measure_key = sm.measure_key
      left join gold.dim_unit u on u.unit_key = m.unit_key
      where sm.measure_key = measure
        and sm.is_enabled
      limit 1
    ) x;
    return result;
  end if;

  if measure is null then
    raise exception 'Missing required measure_key.';
  end if;

  select
    sm.metric_id,
    sm.metric_label,
    sm.aggregation,
    sm.metadata_completeness_status,
    sm.supports_time_comparison,
    sm.supports_geography_comparison
  into metric_row
  from semantic.metric sm
  join gold_bouwen_wonen.dim_housing_indicator hi on hi.measure_key = sm.measure_key
  where sm.measure_key = measure
    and sm.is_enabled
  limit 1;

  if metric_row.metric_id is null then
    raise exception 'Measure is not available in the Bouwen en wonen mart.';
  end if;

  if resolved_calculation_code in ('share_of_total', 'metric_comparison', 'multi_metric_rank') and secondary_measure is null then
    raise exception 'Derived calculation requires secondary_measure_key.';
  end if;

  if secondary_measure is not null and not exists (
    select 1
    from semantic.metric sm
    join gold_bouwen_wonen.dim_housing_indicator hi on hi.measure_key = sm.measure_key
    where sm.measure_key = secondary_measure
      and sm.is_enabled
  ) then
    raise exception 'Secondary measure is not available in the Bouwen en wonen mart.';
  end if;

  if metric_row.aggregation is null or metric_row.aggregation = '' then
    raise exception 'Metric has no approved aggregation rule.';
  end if;

  if intent in ('rank_geographies', 'compare_geographies') and not metric_row.supports_geography_comparison then
    raise exception 'Metric does not support geography comparison.';
  end if;

  if intent = 'trend' and not metric_row.supports_time_comparison then
    raise exception 'Metric does not support time comparison.';
  end if;

  if intent in ('rank_geographies', 'compare_geographies') and not exists (
    select 1
    from semantic.metric_dimension md
    join semantic.dimension d on d.dimension_id = md.dimension_id
    where md.metric_id = metric_row.metric_id
      and d.dimension_code = 'geography'
      and d.is_enabled
      and md.supports_filtering
      and md.supports_grouping
  ) then
    raise exception 'Metric cannot be analysed by geography.';
  end if;

  if intent = 'trend' and not exists (
    select 1
    from semantic.metric_dimension md
    join semantic.dimension d on d.dimension_id = md.dimension_id
    where md.metric_id = metric_row.metric_id
      and d.dimension_code = 'time'
      and d.is_enabled
      and md.supports_grouping
  ) then
    raise exception 'Metric cannot be analysed over time.';
  end if;

  if not exists (
    select 1
    from semantic.join_path
    where from_object = 'gold_bouwen_wonen.fact_housing_observation'
      and from_column = 'measure_key'
      and to_object = 'gold.dim_measure'
      and to_column = 'measure_key'
      and relationship_cardinality = 'many_to_one'
      and is_enabled
  ) then
    raise exception 'Approved join path for fact-to-measure is missing.';
  end if;

  if resolved_calculation_code = 'category_breakdown' then
    select jsonb_build_object(
      'columns', jsonb_build_array('geography_name', 'geography_type', 'calendar_year', 'category_dimension', 'category_name', 'value', 'unit_code', 'unit_name', 'scale_factor'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      select
        f.geography_name,
        f.geography_type,
        f.calendar_year,
        category.dimension_code as category_dimension,
        category.category_name,
        max(f.observation_value * coalesce(u.scale_factor, 1)) as value,
        max(u.unit_code) as unit_code,
        max(u.unit_name) as unit_name,
        max(u.scale_factor) as scale_factor
      from gold_bouwen_wonen.fact_housing_observation f
      join gold.dim_unit u on u.unit_key = f.unit_key
      join gold_bouwen_wonen.bridge_housing_observation_category category
        on category.housing_observation_key = f.housing_observation_key
       and lower(category.dimension_code) = lower(coalesce(nullif(plan->>'category_dimension_code', ''), 'Woningtype'))
      left join gold_bouwen_wonen.bridge_housing_observation_category qualifier
        on qualifier.housing_observation_key = f.housing_observation_key
       and lower(qualifier.dimension_code) = lower(coalesce(nullif(plan->>'category_filter_dimension_code', ''), 'Woningkenmerk'))
      where f.measure_key = measure
        and f.observation_value is not null
        and f.is_missing = false
        and (plan->>'dataset_code' is null or f.dataset_code = plan->>'dataset_code' or f.source_dataset_id = plan->>'dataset_code')
        and (geography_type_filter is null or f.geography_type = geography_type_filter)
        and (year_value is null or f.calendar_year = year_value)
        and (year_start_value is null or f.calendar_year >= year_start_value)
        and (year_end_value is null or f.calendar_year <= year_end_value)
        and (
          jsonb_array_length(coalesce(plan->'geography_names', '[]'::jsonb)) = 0
          or exists (
            select 1
            from jsonb_array_elements_text(plan->'geography_names') requested_geography(name)
            where lower(f.geography_name) = lower(requested_geography.name)
               or lower(regexp_replace(f.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(requested_geography.name, '\s*\([^)]*\)\s*$', ''))
          )
        )
        and (
          plan->>'category_filter_value' is null
          or qualifier.category_name = plan->>'category_filter_value'
          or qualifier.category_code = plan->>'category_filter_value'
        )
        and coalesce(category.category_name, '') not ilike 'Unknown%'
      group by f.geography_name, f.geography_type, f.calendar_year, category.dimension_code, category.category_name
      order by f.geography_name asc, category.category_name asc
      limit limit_value
    ) x;
    return result;
  end if;

  if resolved_calculation_code = 'metric_comparison' then
    select jsonb_build_object(
      'columns', jsonb_build_array('measure_name', 'geography_name', 'geography_type', 'calendar_year', 'value', 'raw_value', 'unit_code', 'unit_name', 'scale_factor'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      select
        m.measure_name,
        f.geography_name,
        f.geography_type,
        f.calendar_year,
        max(f.observation_value * coalesce(u.scale_factor, 1)) as value,
        max(f.observation_value) as raw_value,
        max(u.unit_code) as unit_code,
        max(u.unit_name) as unit_name,
        max(u.scale_factor) as scale_factor
      from gold_bouwen_wonen.fact_housing_observation f
      join gold.dim_measure m on m.measure_key = f.measure_key
      join gold.dim_unit u on u.unit_key = f.unit_key
      where f.measure_key in (measure, secondary_measure)
        and f.observation_value is not null
        and f.is_missing = false
        and coalesce(f.geography_code, '') not in ('GM0000')
        and lower(coalesce(f.geography_name, '')) not like '%niet in te delen%'
        and (geography_type_filter is null or f.geography_type = geography_type_filter)
        and (
          jsonb_array_length(coalesce(plan->'geography_names', '[]'::jsonb)) = 0
          or exists (
            select 1
            from jsonb_array_elements_text(plan->'geography_names') requested_geography(name)
            where lower(f.geography_name) = lower(requested_geography.name)
               or lower(regexp_replace(f.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(requested_geography.name, '\s*\([^)]*\)\s*$', ''))
          )
        )
        and (year_value is null or f.calendar_year = year_value)
        and (year_start_value is null or f.calendar_year >= year_start_value)
        and (year_end_value is null or f.calendar_year <= year_end_value)
      group by m.measure_name, f.measure_key, f.geography_name, f.geography_type, f.calendar_year
      order by f.geography_name asc, f.calendar_year asc, m.measure_name asc
      limit limit_value
    ) x;
    return result;
  end if;

  if resolved_calculation_code = 'share_of_total' then
    select jsonb_build_object(
      'columns', jsonb_build_array('geography_name', 'geography_type', 'calendar_year', 'numerator_value', 'denominator_value', 'share_percent', 'numerator_measure_key', 'denominator_measure_key'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      with numerator as (
        select
          f.geography_name,
          f.geography_type,
          f.calendar_year,
          max(f.observation_value * coalesce(u.scale_factor, 1)) as numerator_value
        from gold_bouwen_wonen.fact_housing_observation f
        join gold.dim_unit u on u.unit_key = f.unit_key
        where f.measure_key = measure
          and f.observation_value is not null
          and f.is_missing = false
          and (geography_type_filter is null or f.geography_type = geography_type_filter)
          and (
            jsonb_array_length(coalesce(plan->'geography_names', '[]'::jsonb)) = 0
            or exists (
              select 1
              from jsonb_array_elements_text(plan->'geography_names') requested_geography(name)
              where lower(f.geography_name) = lower(requested_geography.name)
                 or lower(regexp_replace(f.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(requested_geography.name, '\s*\([^)]*\)\s*$', ''))
            )
          )
          and (year_value is null or f.calendar_year = year_value)
          and (year_start_value is null or f.calendar_year >= year_start_value)
          and (year_end_value is null or f.calendar_year <= year_end_value)
        group by f.geography_name, f.geography_type, f.calendar_year
      ),
      denominator as (
        select
          f.geography_name,
          f.geography_type,
          f.calendar_year,
          max(f.observation_value * coalesce(u.scale_factor, 1)) as denominator_value
        from gold_bouwen_wonen.fact_housing_observation f
        join gold.dim_unit u on u.unit_key = f.unit_key
        where f.measure_key = secondary_measure
          and f.observation_value is not null
          and f.is_missing = false
          and (geography_type_filter is null or f.geography_type = geography_type_filter)
          and (
            jsonb_array_length(coalesce(plan->'geography_names', '[]'::jsonb)) = 0
            or exists (
              select 1
              from jsonb_array_elements_text(plan->'geography_names') requested_geography(name)
              where lower(f.geography_name) = lower(requested_geography.name)
                 or lower(regexp_replace(f.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(requested_geography.name, '\s*\([^)]*\)\s*$', ''))
            )
          )
          and (year_value is null or f.calendar_year = year_value)
          and (year_start_value is null or f.calendar_year >= year_start_value)
          and (year_end_value is null or f.calendar_year <= year_end_value)
        group by f.geography_name, f.geography_type, f.calendar_year
      )
      select
        n.geography_name,
        n.geography_type,
        n.calendar_year,
        n.numerator_value,
        d.denominator_value,
        round((n.numerator_value / nullif(d.denominator_value, 0)) * 100, 2) as share_percent,
        measure::text as numerator_measure_key,
        secondary_measure::text as denominator_measure_key
      from numerator n
      join denominator d on d.geography_name = n.geography_name and d.calendar_year = n.calendar_year
      order by n.geography_name asc, n.calendar_year asc
      limit limit_value
    ) x;
    return result;
  end if;

  if resolved_calculation_code = 'compare_to_average' then
    select jsonb_build_object(
      'columns', jsonb_build_array('geography_name', 'calendar_year', 'value', 'average_value', 'difference_from_average', 'ratio_to_average', 'unit_code'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      with base as (
        select
          f.geography_name,
          f.calendar_year,
          max(f.observation_value * coalesce(u.scale_factor, 1)) as value,
          max(u.unit_code) as unit_code
        from gold_bouwen_wonen.fact_housing_observation f
        join gold.dim_unit u on u.unit_key = f.unit_key
        where f.measure_key = measure
          and f.observation_value is not null
          and f.is_missing = false
          and f.geography_type = coalesce(geography_type_filter, 'municipality')
          and (
            coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
            or coalesce(plan->'category_filters', '{}'::jsonb) = '{}'::jsonb
            or not exists (
              select 1
              from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
              where not exists (
                select 1
                from gold_bouwen_wonen.bridge_housing_observation_category required_category
                where required_category.housing_observation_key = f.housing_observation_key
                  and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
                  and (
                    required_category.category_name = required_filter.category_value
                    or required_category.category_code = required_filter.category_value
                  )
              )
            )
          )
          and (year_value is null or f.calendar_year = year_value)
          and (year_start_value is null or f.calendar_year >= year_start_value)
          and (year_end_value is null or f.calendar_year <= year_end_value)
        group by f.geography_name, f.calendar_year
      ),
      averages as (
        select calendar_year, avg(value) as average_value
        from base
        group by calendar_year
      )
      select
        b.geography_name,
        b.calendar_year,
        b.value,
        round(a.average_value, 2) as average_value,
        round(b.value - a.average_value, 2) as difference_from_average,
        round(b.value / nullif(a.average_value, 0), 4) as ratio_to_average,
        b.unit_code
      from base b
      join averages a on a.calendar_year = b.calendar_year
      where exists (
        select 1
        from jsonb_array_elements_text(plan->'geography_names') requested_geography(name)
        where lower(b.geography_name) = lower(requested_geography.name)
           or lower(regexp_replace(b.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(requested_geography.name, '\s*\([^)]*\)\s*$', ''))
      )
      order by b.geography_name asc, b.calendar_year asc
      limit limit_value
    ) x;
    return result;
  end if;

  if resolved_calculation_code = 'multi_metric_rank' then
    select jsonb_build_object(
      'columns', jsonb_build_array('geography_name', 'calendar_year', 'primary_value', 'secondary_value', 'primary_rank', 'secondary_rank', 'combined_rank_score'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      with primary_values as (
        select f.geography_name, f.geography_code, f.calendar_year, max(f.observation_value * coalesce(u.scale_factor, 1)) as primary_value
        from gold_bouwen_wonen.fact_housing_observation f
        join gold.dim_unit u on u.unit_key = f.unit_key
        where f.measure_key = measure
          and f.observation_value is not null
          and f.is_missing = false
          and (geography_type_filter is null or f.geography_type = geography_type_filter)
          and (
            coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
            or coalesce(plan->'category_filters', '{}'::jsonb) = '{}'::jsonb
            or not exists (
              select 1
              from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
              where not exists (
                select 1
                from gold_bouwen_wonen.bridge_housing_observation_category required_category
                where required_category.housing_observation_key = f.housing_observation_key
                  and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
                  and (
                    required_category.category_name = required_filter.category_value
                    or required_category.category_code = required_filter.category_value
                  )
              )
            )
          )
          and (year_value is null or f.calendar_year = year_value)
        group by f.geography_name, f.geography_code, f.calendar_year
      ),
      secondary_values as (
        select f.geography_name, f.calendar_year, max(f.observation_value * coalesce(u.scale_factor, 1)) as secondary_value
        from gold_bouwen_wonen.fact_housing_observation f
        join gold.dim_unit u on u.unit_key = f.unit_key
        where f.measure_key = secondary_measure
          and f.observation_value is not null
          and f.is_missing = false
          and (geography_type_filter is null or f.geography_type = geography_type_filter)
          and (year_value is null or f.calendar_year = year_value)
        group by f.geography_name, f.calendar_year
      ),
      joined as (
        select p.geography_name, p.calendar_year, p.primary_value, s.secondary_value
        from primary_values p
        join secondary_values s on s.geography_name = p.geography_name and s.calendar_year = p.calendar_year
      ),
      ranked as (
        select
          geography_name,
          calendar_year,
          primary_value,
          secondary_value,
          rank() over (partition by calendar_year order by primary_value desc nulls last) as primary_rank,
          rank() over (partition by calendar_year order by secondary_value asc nulls last) as secondary_rank
        from joined
      )
      select
        geography_name,
        calendar_year,
        primary_value,
        secondary_value,
        primary_rank,
        secondary_rank,
        primary_rank + secondary_rank as combined_rank_score
      from ranked
      order by combined_rank_score asc, primary_rank asc
      limit limit_value
    ) x;
    return result;
  end if;

  if resolved_calculation_code = 'change_rank' then
    if year_start_value is null or year_end_value is null then
      raise exception 'Change ranking requires year_start and year_end.';
    end if;

    select jsonb_build_object(
      'columns', jsonb_build_array('geography_name', 'geography_type', 'start_year', 'end_year', 'start_value', 'end_value', 'absolute_change', 'percentage_change'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      with values_by_year as (
        select
          f.geography_name,
          f.geography_type,
          f.calendar_year,
          max(f.observation_value * coalesce(u.scale_factor, 1)) as value
        from gold_bouwen_wonen.fact_housing_observation f
        join gold.dim_unit u on u.unit_key = f.unit_key
        where f.measure_key = measure
          and f.observation_value is not null
          and f.is_missing = false
          and (geography_type_filter is null or f.geography_type = geography_type_filter)
          and (
            coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
            or coalesce(plan->'category_filters', '{}'::jsonb) = '{}'::jsonb
            or not exists (
              select 1
              from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
              where not exists (
                select 1
                from gold_bouwen_wonen.bridge_housing_observation_category required_category
                where required_category.housing_observation_key = f.housing_observation_key
                  and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
                  and (
                    required_category.category_name = required_filter.category_value
                    or required_category.category_code = required_filter.category_value
                  )
              )
            )
          )
          and f.calendar_year in (year_start_value, year_end_value)
        group by f.geography_name, f.geography_type, f.calendar_year
      )
      select
        s.geography_name,
        s.geography_type,
        year_start_value as start_year,
        year_end_value as end_year,
        s.value as start_value,
        e.value as end_value,
        e.value - s.value as absolute_change,
        round(((e.value - s.value) / nullif(s.value, 0)) * 100, 2) as percentage_change
      from values_by_year s
      join values_by_year e on e.geography_name = s.geography_name
      where s.calendar_year = year_start_value
        and e.calendar_year = year_end_value
      order by absolute_change desc nulls last
      limit limit_value
    ) x;
    return result;
  end if;

  if intent = 'rank_geographies' then
    select jsonb_build_object(
      'columns', jsonb_build_array('geography_name', 'geography_code', 'geography_type', 'calendar_year', 'value', 'raw_value', 'unit_code', 'unit_name', 'scale_factor'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      select
          f.geography_name,
          f.geography_code,
          f.geography_type,
          f.calendar_year,
          max(f.observation_value * coalesce(u.scale_factor, 1)) as value,
          max(f.observation_value) as raw_value,
          max(u.unit_code) as unit_code,
          max(u.unit_name) as unit_name,
          max(u.scale_factor) as scale_factor
        from gold_bouwen_wonen.fact_housing_observation f
        join gold.dim_unit u on u.unit_key = f.unit_key
        where f.measure_key = measure
          and f.observation_value is not null
          and f.is_missing = false
          and coalesce(f.geography_code, '') not in ('GM0000')
          and lower(coalesce(f.geography_name, '')) not like '%niet in te delen%'
          and (geography_type_filter is null or f.geography_type = geography_type_filter)
          and (
            coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
            or coalesce(plan->'category_filters', '{}'::jsonb) = '{}'::jsonb
            or not exists (
              select 1
              from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
              where not exists (
                select 1
                from gold_bouwen_wonen.bridge_housing_observation_category required_category
                where required_category.housing_observation_key = f.housing_observation_key
                  and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
                  and (
                    required_category.category_name = required_filter.category_value
                    or required_category.category_code = required_filter.category_value
                  )
              )
            )
          )
          and (year_value is null or f.calendar_year = year_value)
          and (year_start_value is null or f.calendar_year >= year_start_value)
          and (year_end_value is null or f.calendar_year <= year_end_value)
          and (
            jsonb_array_length(coalesce(plan->'excluded_geography_names', '[]'::jsonb)) = 0
            or not exists (
              select 1
              from jsonb_array_elements_text(plan->'excluded_geography_names') excluded_geography(name)
              where lower(f.geography_name) = lower(excluded_geography.name)
                 or lower(regexp_replace(f.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(excluded_geography.name, '\s*\([^)]*\)\s*$', ''))
            )
          )
        group by f.geography_name, f.geography_code, f.geography_type, f.calendar_year
        having
          value_filter_value is null
          or case value_filter_operator
            when 'lt' then max(f.observation_value * coalesce(u.scale_factor, 1)) < value_filter_value
            when 'lte' then max(f.observation_value * coalesce(u.scale_factor, 1)) <= value_filter_value
            when 'gt' then max(f.observation_value * coalesce(u.scale_factor, 1)) > value_filter_value
            when 'gte' then max(f.observation_value * coalesce(u.scale_factor, 1)) >= value_filter_value
            else true
          end
        order by
          case when sort_direction = 'asc' then max(f.observation_value * coalesce(u.scale_factor, 1)) end asc nulls last,
          case when sort_direction = 'desc' then max(f.observation_value * coalesce(u.scale_factor, 1)) end desc nulls last
        limit limit_value
    ) x;
    return result;
  end if;

  if intent = 'compare_geographies' then
    select jsonb_build_object(
      'columns', jsonb_build_array('geography_name', 'geography_type', 'calendar_year', 'value', 'raw_value', 'unit_code', 'unit_name', 'scale_factor'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      select
        f.geography_name,
        f.geography_type,
        f.calendar_year,
        max(f.observation_value * coalesce(u.scale_factor, 1)) as value,
        max(f.observation_value) as raw_value,
        max(u.unit_code) as unit_code,
        max(u.unit_name) as unit_name,
        max(u.scale_factor) as scale_factor
      from gold_bouwen_wonen.fact_housing_observation f
      join gold.dim_unit u on u.unit_key = f.unit_key
      where f.measure_key = measure
        and f.observation_value is not null
        and f.is_missing = false
        and (geography_type_filter is null or f.geography_type = geography_type_filter)
        and (
          coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
          or coalesce(plan->'category_filters', '{}'::jsonb) = '{}'::jsonb
          or not exists (
            select 1
            from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
            where not exists (
              select 1
              from gold_bouwen_wonen.bridge_housing_observation_category required_category
              where required_category.housing_observation_key = f.housing_observation_key
                and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
                and (
                  required_category.category_name = required_filter.category_value
                  or required_category.category_code = required_filter.category_value
                )
            )
          )
        )
        and (
          jsonb_array_length(coalesce(plan->'geography_names', '[]'::jsonb)) = 0
          or exists (
            select 1
            from jsonb_array_elements_text(plan->'geography_names') requested_geography(name)
            where lower(f.geography_name) = lower(requested_geography.name)
               or lower(regexp_replace(f.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(requested_geography.name, '\s*\([^)]*\)\s*$', ''))
          )
        )
        and (
          jsonb_array_length(coalesce(plan->'excluded_geography_names', '[]'::jsonb)) = 0
          or not exists (
            select 1
            from jsonb_array_elements_text(plan->'excluded_geography_names') excluded_geography(name)
            where lower(f.geography_name) = lower(excluded_geography.name)
               or lower(regexp_replace(f.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(excluded_geography.name, '\s*\([^)]*\)\s*$', ''))
          )
        )
        and (year_value is null or f.calendar_year = year_value)
        and (year_start_value is null or f.calendar_year >= year_start_value)
        and (year_end_value is null or f.calendar_year <= year_end_value)
      group by f.geography_name, f.geography_type, f.calendar_year
      having
        value_filter_value is null
        or case value_filter_operator
          when 'lt' then max(f.observation_value * coalesce(u.scale_factor, 1)) < value_filter_value
          when 'lte' then max(f.observation_value * coalesce(u.scale_factor, 1)) <= value_filter_value
          when 'gt' then max(f.observation_value * coalesce(u.scale_factor, 1)) > value_filter_value
          when 'gte' then max(f.observation_value * coalesce(u.scale_factor, 1)) >= value_filter_value
          else true
        end
      order by f.geography_name asc, f.calendar_year asc
      limit limit_value
    ) x;
    return result;
  end if;

  if intent = 'trend' then
    select jsonb_build_object(
      'columns', jsonb_build_array('calendar_year', 'value', 'raw_value', 'unit_code', 'unit_name', 'scale_factor'),
      'rows', coalesce(jsonb_agg(to_jsonb(x)), '[]'::jsonb)
    )
    into result
    from (
      select
        f.calendar_year,
        max(f.observation_value * coalesce(u.scale_factor, 1)) as value,
        max(f.observation_value) as raw_value,
        max(u.unit_code) as unit_code,
        max(u.unit_name) as unit_name,
        max(u.scale_factor) as scale_factor
      from gold_bouwen_wonen.fact_housing_observation f
      join gold.dim_unit u on u.unit_key = f.unit_key
      where f.measure_key = measure
        and f.observation_value is not null
        and f.is_missing = false
        and f.calendar_year is not null
        and (geography_type_filter is null or f.geography_type = geography_type_filter)
        and (
          coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
          or coalesce(plan->'category_filters', '{}'::jsonb) = '{}'::jsonb
          or not exists (
            select 1
            from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
            where not exists (
              select 1
              from gold_bouwen_wonen.bridge_housing_observation_category required_category
              where required_category.housing_observation_key = f.housing_observation_key
                and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
                and (
                  required_category.category_name = required_filter.category_value
                  or required_category.category_code = required_filter.category_value
                )
            )
          )
        )
        and (year_value is null or f.calendar_year = year_value)
        and (year_start_value is null or f.calendar_year >= year_start_value)
        and (year_end_value is null or f.calendar_year <= year_end_value)
        and (
          jsonb_array_length(coalesce(plan->'geography_names', '[]'::jsonb)) = 0
          or exists (
            select 1
            from jsonb_array_elements_text(plan->'geography_names') requested_geography(name)
            where lower(f.geography_name) = lower(requested_geography.name)
               or lower(regexp_replace(f.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(requested_geography.name, '\s*\([^)]*\)\s*$', ''))
          )
        )
      group by f.calendar_year
      order by f.calendar_year asc
      limit limit_value
    ) x;
    return result;
  end if;

  raise exception 'Unhandled query intent.';
end;
$$;

drop function if exists public.guara_check_query_availability(jsonb);
create or replace function public.guara_check_query_availability(plan jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, gold, gold_bouwen_wonen, semantic
as $$
declare
  measure bigint := nullif(plan->>'measure_key', '')::bigint;
  dataset_filter text := nullif(plan->>'dataset_code', '');
  year_value integer := nullif(plan->>'year', '')::integer;
  year_start_value integer := nullif(plan->>'year_start', '')::integer;
  year_end_value integer := nullif(plan->>'year_end', '')::integer;
  geography_type_filter text := nullif(plan->>'geography_type', '');
  metric_row_count bigint := 0;
  dataset_row_count bigint := 0;
  grain_row_count bigint := 0;
  matching_row_count bigint := 0;
  available_years jsonb := '[]'::jsonb;
  available_geography_types jsonb := '[]'::jsonb;
  category_hash text := coalesce(nullif(plan->>'category_filter_hash', ''), md5(coalesce((plan->'category_filters')::text, '{}'::text)));
  indexed_metric_rows bigint := 0;
begin
  if measure is null then
    return jsonb_build_object(
      'metric_available', false,
      'dataset_available', false,
      'grain_available', false,
      'period_available', false,
      'matching_rows', 0,
      'reason', 'missing_measure_key'
    );
  end if;

  select count(*)
  into indexed_metric_rows
  from semantic.contract_availability a
  where a.measure_key = measure
    and (dataset_filter is null or a.dataset_code = dataset_filter)
    and (geography_type_filter is null or a.geography_type = geography_type_filter)
    and (
      case
        when coalesce(jsonb_typeof(plan->'category_filters'), '') = 'object' then a.category_filter_hash = category_hash
        else a.category_filter_hash = md5('{}')
      end
    );

  if indexed_metric_rows > 0 then
    select
      coalesce(sum(a.row_count), 0),
      coalesce(sum(a.row_count) filter (where dataset_filter is null or a.dataset_code = dataset_filter), 0),
      coalesce(sum(a.row_count) filter (where geography_type_filter is null or a.geography_type = geography_type_filter), 0),
      coalesce(sum(a.row_count) filter (
        where (year_value is null or a.calendar_year = year_value)
          and (year_start_value is null or a.calendar_year >= year_start_value)
          and (year_end_value is null or a.calendar_year <= year_end_value)
      ), 0)
    into metric_row_count, dataset_row_count, grain_row_count, matching_row_count
    from semantic.contract_availability a
    where a.measure_key = measure
      and (dataset_filter is null or a.dataset_code = dataset_filter)
      and (geography_type_filter is null or a.geography_type = geography_type_filter)
      and (
        case
          when coalesce(jsonb_typeof(plan->'category_filters'), '') = 'object' then a.category_filter_hash = category_hash
          else a.category_filter_hash = md5('{}')
        end
      );

    select coalesce(jsonb_agg(calendar_year order by calendar_year), '[]'::jsonb)
    into available_years
    from (
      select distinct a.calendar_year
      from semantic.contract_availability a
      where a.measure_key = measure
        and (dataset_filter is null or a.dataset_code = dataset_filter)
        and (geography_type_filter is null or a.geography_type = geography_type_filter)
        and a.row_count > 0
        and a.calendar_year is not null
        and (
          case
            when coalesce(jsonb_typeof(plan->'category_filters'), '') = 'object' then a.category_filter_hash = category_hash
            else a.category_filter_hash = md5('{}')
          end
        )
    ) years;

    select coalesce(jsonb_agg(geography_type order by geography_type), '[]'::jsonb)
    into available_geography_types
    from (
      select distinct a.geography_type
      from semantic.contract_availability a
      where a.measure_key = measure
        and (dataset_filter is null or a.dataset_code = dataset_filter)
        and a.row_count > 0
        and (
          case
            when coalesce(jsonb_typeof(plan->'category_filters'), '') = 'object' then a.category_filter_hash = category_hash
            else a.category_filter_hash = md5('{}')
          end
        )
    ) geography_types;

    return jsonb_build_object(
      'metric_available', metric_row_count > 0,
      'dataset_available', dataset_row_count > 0,
      'grain_available', grain_row_count > 0,
      'period_available', matching_row_count > 0,
      'metric_row_count', metric_row_count,
      'dataset_row_count', dataset_row_count,
      'grain_row_count', grain_row_count,
      'matching_rows', matching_row_count,
      'available_years', available_years,
      'available_geography_types', available_geography_types,
      'availability_source', 'semantic.contract_availability'
    );
  end if;

  select count(*)
  into metric_row_count
  from gold_bouwen_wonen.fact_housing_observation f
  where f.measure_key = measure
    and f.observation_value is not null
    and f.is_missing = false;

  select count(*)
  into dataset_row_count
  from gold_bouwen_wonen.fact_housing_observation f
  where f.measure_key = measure
    and (dataset_filter is null or f.dataset_code = dataset_filter)
    and f.observation_value is not null
    and f.is_missing = false;

  select count(*)
  into grain_row_count
  from gold_bouwen_wonen.fact_housing_observation f
  where f.measure_key = measure
    and (dataset_filter is null or f.dataset_code = dataset_filter)
    and (geography_type_filter is null or f.geography_type = geography_type_filter)
    and f.observation_value is not null
    and f.is_missing = false;

  select count(*)
  into matching_row_count
  from gold_bouwen_wonen.fact_housing_observation f
  where f.measure_key = measure
    and (dataset_filter is null or f.dataset_code = dataset_filter)
    and (geography_type_filter is null or f.geography_type = geography_type_filter)
    and f.observation_value is not null
    and f.is_missing = false
    and (year_value is null or f.calendar_year = year_value)
    and (year_start_value is null or f.calendar_year >= year_start_value)
    and (year_end_value is null or f.calendar_year <= year_end_value)
    and (
      jsonb_array_length(coalesce(plan->'geography_names', '[]'::jsonb)) = 0
      or exists (
        select 1
        from jsonb_array_elements_text(plan->'geography_names') requested_geography(name)
        where lower(f.geography_name) = lower(requested_geography.name)
           or lower(regexp_replace(f.geography_name, '\s*\([^)]*\)\s*$', '')) = lower(regexp_replace(requested_geography.name, '\s*\([^)]*\)\s*$', ''))
      )
    )
    and (
      coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
      or not exists (
        select 1
        from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
        where not exists (
          select 1
          from gold_bouwen_wonen.bridge_housing_observation_category required_category
          where required_category.housing_observation_key = f.housing_observation_key
            and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
            and (
              required_category.category_name = required_filter.category_value
              or required_category.category_code = required_filter.category_value
            )
        )
      )
    );

  select coalesce(jsonb_agg(calendar_year order by calendar_year), '[]'::jsonb)
  into available_years
  from (
    select distinct f.calendar_year
    from gold_bouwen_wonen.fact_housing_observation f
    where f.measure_key = measure
      and (dataset_filter is null or f.dataset_code = dataset_filter)
      and (geography_type_filter is null or f.geography_type = geography_type_filter)
      and f.observation_value is not null
      and f.is_missing = false
      and f.calendar_year is not null
      and (
        coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
        or not exists (
          select 1
          from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
          where not exists (
            select 1
            from gold_bouwen_wonen.bridge_housing_observation_category required_category
            where required_category.housing_observation_key = f.housing_observation_key
              and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
              and (
                required_category.category_name = required_filter.category_value
                or required_category.category_code = required_filter.category_value
              )
          )
        )
      )
  ) years;

  select coalesce(jsonb_agg(geography_type order by geography_type), '[]'::jsonb)
  into available_geography_types
  from (
    select distinct f.geography_type
    from gold_bouwen_wonen.fact_housing_observation f
    where f.measure_key = measure
      and (dataset_filter is null or f.dataset_code = dataset_filter)
      and f.observation_value is not null
      and f.is_missing = false
      and f.geography_type is not null
      and (
        coalesce(jsonb_typeof(plan->'category_filters'), '') <> 'object'
        or not exists (
          select 1
          from jsonb_each_text(plan->'category_filters') required_filter(dimension_code, category_value)
          where not exists (
            select 1
            from gold_bouwen_wonen.bridge_housing_observation_category required_category
            where required_category.housing_observation_key = f.housing_observation_key
              and lower(required_category.dimension_code) = lower(required_filter.dimension_code)
              and (
                required_category.category_name = required_filter.category_value
                or required_category.category_code = required_filter.category_value
              )
          )
        )
      )
  ) geography_types;

  return jsonb_build_object(
    'metric_available', metric_row_count > 0,
    'dataset_available', dataset_row_count > 0,
    'grain_available', grain_row_count > 0,
    'period_available', matching_row_count > 0,
    'metric_row_count', metric_row_count,
    'dataset_row_count', dataset_row_count,
    'grain_row_count', grain_row_count,
    'matching_rows', matching_row_count,
    'available_years', available_years,
    'available_geography_types', available_geography_types
  );
end;
$$;

grant execute on function public.guara_execute_query_plan(jsonb) to anon, authenticated;
grant execute on function public.guara_check_query_availability(jsonb) to anon, authenticated;

drop function if exists public.guara_record_answer_provenance(text, text, jsonb, jsonb, jsonb, numeric);
create or replace function public.guara_record_answer_provenance(
  question text,
  intent text,
  query_plan jsonb,
  result_summary jsonb,
  sources jsonb,
  confidence numeric
)
returns uuid
language plpgsql
volatile
security definer
set search_path = public, semantic
as $$
declare
  next_id uuid;
begin
  insert into semantic.answer_provenance (
    question, intent, query_plan, compiled_sql_fingerprint, result_summary, sources, confidence
  )
  values (
    question,
    intent,
    query_plan,
    encode(sha256(convert_to(query_plan::text, 'UTF8')), 'hex'),
    coalesce(result_summary, '{}'::jsonb),
    coalesce(sources, '[]'::jsonb),
    confidence
  )
  returning answer_id into next_id;

  return next_id;
end;
$$;

drop function if exists public.guara_save_analysis(uuid, text, text);
create or replace function public.guara_save_analysis(
  answer_id uuid,
  title text,
  summary text default null
)
returns uuid
language plpgsql
volatile
security definer
set search_path = public, semantic
as $$
declare
  next_id uuid;
begin
  insert into semantic.saved_analysis (answer_id, title, question, summary, query_plan, sources)
  select
    a.answer_id,
    coalesce(nullif(title, ''), left(a.question, 120)),
    a.question,
    summary,
    a.query_plan,
    a.sources
  from semantic.answer_provenance a
  where a.answer_id = guara_save_analysis.answer_id
  returning analysis_id into next_id;

  return next_id;
end;
$$;

drop function if exists public.guara_convert_answer_to_evidence(uuid, text, text);
create or replace function public.guara_convert_answer_to_evidence(
  answer_id uuid,
  title text,
  claim text default null
)
returns uuid
language plpgsql
volatile
security definer
set search_path = public, semantic
as $$
declare
  next_id uuid;
begin
  insert into semantic.evidence_conversion (answer_id, title, claim, sources)
  select
    a.answer_id,
    coalesce(nullif(title, ''), left(a.question, 120)),
    claim,
    a.sources
  from semantic.answer_provenance a
  where a.answer_id = guara_convert_answer_to_evidence.answer_id
  returning evidence_id into next_id;

  return next_id;
end;
$$;

grant usage on schema semantic to anon, authenticated;

grant select on table
  semantic.semantic_dataset_contract,
  semantic.semantic_dataset_profile,
  semantic.semantic_measure_profile,
  semantic.semantic_dimension_profile,
  semantic.semantic_category_profile,
  semantic.semantic_grain_profile,
  semantic.semantic_metric_dimension_compatibility,
  semantic.metric_preference,
  semantic.metric_grain,
  semantic.metric_contract,
  semantic.concept,
  semantic.concept_metric_binding,
  semantic.dimension_contract,
  semantic.category_value_contract,
  semantic.contract_availability,
  semantic.golden_question
to anon, authenticated;

drop function if exists public.guara_semantic_contract_context(text, integer, integer, integer);
create or replace function public.guara_semantic_contract_context(
  domain_id text default 'bouwen-en-wonen',
  contract_limit integer default 1000,
  measure_limit integer default 5000,
  grain_limit integer default 10000
)
returns jsonb
language sql
stable
security definer
set search_path = public, semantic
as $$
  select jsonb_build_object(
    'contracts', coalesce((
      select jsonb_agg(to_jsonb(contract_row))
      from (
        select
          dataset_code,
          dataset_title,
          domain_id,
          data_availability_status,
          profile_depth,
          default_measure_key::text as default_measure_key,
          default_measure_name,
          default_unit_code,
          default_breakdown_dimension,
          default_filter_dimension,
          default_filter_value,
          geography_types,
          period_types,
          dimension_codes,
          min_year,
          max_year,
          supported_query_shapes,
          contract_status
        from semantic.semantic_dataset_contract
        where (guara_semantic_contract_context.domain_id is null or semantic_dataset_contract.domain_id = guara_semantic_contract_context.domain_id)
          and coalesce(contract_status, '') <> 'incomplete'
        order by dataset_code
        limit contract_limit
      ) contract_row
    ), '[]'::jsonb),
    'metric_contracts', coalesce((
      select jsonb_agg(to_jsonb(metric_contract_row))
      from (
        select
          metric_code,
          label,
          description,
          domain_id,
          measure_key::text as measure_key,
          dataset_codes,
          unit_code,
          aggregation,
          valid_grains,
          default_grain,
          synonyms,
          exclusions,
          supports,
          category_filters,
          selection_priority,
          metadata_origin,
          contract_status,
          execution_status,
          semantic_quality_status,
          availability_status,
          availability_checked_at
        from semantic.metric_contract
        where is_active
          and (guara_semantic_contract_context.domain_id is null or metric_contract.domain_id = guara_semantic_contract_context.domain_id)
        order by selection_priority, metric_code
        limit measure_limit
      ) metric_contract_row
    ), '[]'::jsonb),
    'concepts', coalesce((
      select jsonb_agg(to_jsonb(concept_row))
      from (
        select
          concept_code,
          label,
          description,
          domain_id,
          language_code,
          synonyms,
          exclusions,
          required_unit_code,
          default_grain,
          valid_grains,
          supported_operations,
          ambiguity_policy,
          metadata_origin
        from semantic.concept
        where is_active
          and (guara_semantic_contract_context.domain_id is null or concept.domain_id = guara_semantic_contract_context.domain_id)
        order by concept_code
        limit measure_limit
      ) concept_row
    ), '[]'::jsonb),
    'concept_metric_bindings', coalesce((
      select jsonb_agg(to_jsonb(binding_row))
      from (
        select
          concept_code,
          metric_code,
          measure_key::text as measure_key,
          dataset_code,
          binding_role,
          priority,
          required_unit_code,
          allowed_grains,
          category_filters,
          union_rule_code,
          selection_reason,
          metadata_origin
        from semantic.concept_metric_binding
        where is_active
        order by concept_code, priority, metric_code
        limit measure_limit
      ) binding_row
    ), '[]'::jsonb),
    'dimension_contracts', coalesce((
      select jsonb_agg(to_jsonb(dimension_contract_row))
      from (
        select
          dimension_code,
          dataset_code,
          domain_id,
          label,
          description,
          dimension_role,
          canonical_total_value,
          valid_values,
          value_synonyms,
          resolution_rules,
          supports_grouping,
          supports_filtering,
          metadata_origin,
          contract_status
        from semantic.dimension_contract
        where is_active
          and (guara_semantic_contract_context.domain_id is null or dimension_contract.domain_id = guara_semantic_contract_context.domain_id)
        order by dataset_code nulls first, dimension_code
        limit measure_limit
      ) dimension_contract_row
    ), '[]'::jsonb),
    'category_value_contracts', coalesce((
      select jsonb_agg(to_jsonb(category_value_contract_row))
      from (
        select
          contract_code,
          domain_id,
          dataset_code,
          metric_code,
          measure_key::text as measure_key,
          measure_name,
          unit_code,
          aggregation,
          dimension_code,
          category_code,
          category_name,
          label,
          description,
          synonyms,
          category_filters,
          valid_grains,
          default_grain,
          supports,
          is_total,
          is_unknown,
          selection_priority,
          metadata_origin,
          contract_status,
          execution_status,
          semantic_quality_status,
          availability_status,
          availability_checked_at
        from semantic.category_value_contract
        where is_active
          and (guara_semantic_contract_context.domain_id is null or category_value_contract.domain_id = guara_semantic_contract_context.domain_id)
        order by selection_priority, dataset_code, dimension_code, category_name
        limit measure_limit
      ) category_value_contract_row
    ), '[]'::jsonb),
    'measures', coalesce((
      select jsonb_agg(to_jsonb(measure_row))
      from (
        select
          dataset_code,
          measure_key::text as measure_key,
          measure_code,
          measure_name,
          measure_description,
          unit_code,
          unit_name,
          default_aggregation,
          can_enable_metric,
          profile_depth,
          fact_row_count,
          populated_fact_row_count,
          min_year,
          max_year,
          geography_types,
          period_types
        from semantic.semantic_measure_profile
        where coalesce(can_enable_metric, true)
          and exists (
            select 1
            from semantic.semantic_dataset_contract c
            where c.dataset_code = semantic_measure_profile.dataset_code
              and (guara_semantic_contract_context.domain_id is null or c.domain_id = guara_semantic_contract_context.domain_id)
          )
        order by dataset_code, measure_name
        limit measure_limit
      ) measure_row
    ), '[]'::jsonb),
    'grains', coalesce((
      select jsonb_agg(to_jsonb(grain_row))
      from (
        select
          measure_key::text as measure_key,
          geography_type,
          period_type,
          min_year,
          max_year,
          fact_row_count,
          is_supported,
          profile_depth
        from semantic.semantic_grain_profile
        where exists (
          select 1
          from semantic.semantic_dataset_contract c
          where c.dataset_code = semantic_grain_profile.dataset_code
            and (guara_semantic_contract_context.domain_id is null or c.domain_id = guara_semantic_contract_context.domain_id)
        )
        order by measure_key, geography_type, period_type
        limit grain_limit
      ) grain_row
    ), '[]'::jsonb),
    'curated_grains', coalesce((
      select jsonb_agg(to_jsonb(curated_grain_row))
      from (
        select
          measure_key::text as measure_key,
          geography_type,
          period_type,
          min_year,
          max_year,
          fact_row_count,
          is_supported,
          null::text as profile_depth
        from semantic.metric_grain
        where exists (
          select 1
          from semantic.semantic_dataset_contract c
          where c.dataset_code = metric_grain.dataset_code
            and (guara_semantic_contract_context.domain_id is null or c.domain_id = guara_semantic_contract_context.domain_id)
        )
        order by measure_key, geography_type, period_type
        limit grain_limit
      ) curated_grain_row
    ), '[]'::jsonb),
    'metric_preferences', coalesce((
      select jsonb_agg(to_jsonb(preference_row))
      from (
        select
          normalized_metric_label,
          geography_type,
          calculation_code,
          preferred_measure_key::text as preferred_measure_key,
          preferred_dataset_code,
          priority,
          reason
        from semantic.metric_preference
        where is_active
          and (guara_semantic_contract_context.domain_id is null or metric_preference.domain_id = guara_semantic_contract_context.domain_id)
        order by priority, normalized_metric_label
        limit 5000
      ) preference_row
    ), '[]'::jsonb)
  );
$$;

grant execute on function public.guara_semantic_contract_context(text, integer, integer, integer) to anon, authenticated;
