create schema if not exists semantic;

create table if not exists semantic.metric_relationship_profile (
  metric_relationship_profile_id bigint generated by default as identity primary key,
  metric_code_a text not null,
  metric_code_b text not null,
  measure_key_a bigint not null,
  measure_key_b bigint not null,
  dataset_code_a text not null,
  dataset_code_b text not null,
  domain_id_a text,
  domain_id_b text,
  label_a text not null,
  label_b text not null,
  unit_code_a text,
  unit_code_b text,
  grain text not null,
  geography_type text not null,
  period_type text not null default 'year',
  calendar_year integer not null,
  observation_count integer not null,
  geography_count integer not null,
  pearson_correlation numeric,
  relationship_direction text not null,
  relationship_strength text not null,
  relationship_type text not null default 'association',
  causality_status text not null default 'not_established',
  missingness_rate numeric,
  quality_status text not null,
  interpretation_warning text,
  metadata jsonb not null default '{}'::jsonb,
  computed_at timestamptz not null default now(),
  unique (metric_code_a, metric_code_b, grain, calendar_year)
);

create index if not exists metric_relationship_profile_lookup_idx
  on semantic.metric_relationship_profile(grain, calendar_year, abs(pearson_correlation) desc nulls last);

create index if not exists metric_relationship_profile_metric_a_idx
  on semantic.metric_relationship_profile(metric_code_a, grain, calendar_year);

create index if not exists metric_relationship_profile_metric_b_idx
  on semantic.metric_relationship_profile(metric_code_b, grain, calendar_year);

create index if not exists metric_relationship_profile_domains_idx
  on semantic.metric_relationship_profile(domain_id_a, domain_id_b, relationship_strength, calendar_year);

alter table semantic.metric_relationship_profile enable row level security;

drop policy if exists "semantic_metric_relationship_profile_read_public" on semantic.metric_relationship_profile;
create policy "semantic_metric_relationship_profile_read_public"
  on semantic.metric_relationship_profile for select
  using (true);
