create schema if not exists semantic;

create table if not exists semantic.metric_alias (
  metric_alias_id bigint generated by default as identity primary key,
  alias text not null,
  normalized_alias text not null,
  language_code text not null default 'nl',
  domain_id text not null default '',
  measure_key bigint,
  dataset_code text,
  priority integer not null default 100,
  metadata_origin text not null default 'curated',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_alias, language_code, domain_id, measure_key)
);

create table if not exists semantic.metric_preference (
  metric_preference_id bigint generated by default as identity primary key,
  preference_code text not null unique,
  normalized_metric_label text not null,
  domain_id text,
  geography_type text,
  calculation_code text,
  preferred_measure_key bigint not null,
  preferred_dataset_code text,
  priority integer not null default 100,
  reason text,
  metadata_origin text not null default 'curated',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists semantic.metric_grain (
  metric_grain_id bigint generated by default as identity primary key,
  measure_key bigint not null,
  dataset_code text,
  geography_type text not null,
  period_type text not null default '',
  min_year integer,
  max_year integer,
  fact_row_count bigint not null default 0,
  is_supported boolean not null default true,
  metadata_origin text not null default 'generated',
  updated_at timestamptz not null default now(),
  unique (measure_key, geography_type, period_type)
);

create table if not exists semantic.geography_alias (
  geography_alias_id bigint generated by default as identity primary key,
  alias text not null,
  normalized_alias text not null,
  language_code text not null default 'nl',
  geography_type text not null,
  geography_name text not null,
  geography_code text,
  priority integer not null default 100,
  metadata_origin text not null default 'curated',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_alias, language_code, geography_type, geography_name)
);

create table if not exists semantic.golden_question (
  golden_question_id bigint generated by default as identity primary key,
  question text not null unique,
  domain_id text not null default 'bouwen-en-wonen',
  expected_intent text not null,
  expected_calculation_code text,
  expected_measure_label text,
  expected_secondary_measure_label text,
  expected_geography_names text[] not null default '{}',
  expected_geography_type text,
  expected_year integer,
  expected_year_start integer,
  expected_year_end integer,
  expected_result_shape jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  metadata_origin text not null default 'curated',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists semantic_metric_alias_lookup_idx
  on semantic.metric_alias(normalized_alias, language_code, domain_id, priority);

create index if not exists semantic_metric_preference_lookup_idx
  on semantic.metric_preference(normalized_metric_label, domain_id, geography_type, calculation_code, priority)
  where is_active;

create index if not exists semantic_metric_grain_lookup_idx
  on semantic.metric_grain(measure_key, geography_type, period_type);

create index if not exists semantic_geography_alias_lookup_idx
  on semantic.geography_alias(normalized_alias, geography_type, priority);

alter table semantic.metric_alias enable row level security;
alter table semantic.metric_preference enable row level security;
alter table semantic.metric_grain enable row level security;
alter table semantic.geography_alias enable row level security;
alter table semantic.golden_question enable row level security;

drop policy if exists "semantic_metric_alias_read_public" on semantic.metric_alias;
create policy "semantic_metric_alias_read_public" on semantic.metric_alias for select using (true);

drop policy if exists "semantic_metric_preference_read_public" on semantic.metric_preference;
create policy "semantic_metric_preference_read_public" on semantic.metric_preference for select using (is_active);

drop policy if exists "semantic_metric_grain_read_public" on semantic.metric_grain;
create policy "semantic_metric_grain_read_public" on semantic.metric_grain for select using (true);

drop policy if exists "semantic_geography_alias_read_public" on semantic.geography_alias;
create policy "semantic_geography_alias_read_public" on semantic.geography_alias for select using (true);

drop policy if exists "semantic_golden_question_read_public" on semantic.golden_question;
create policy "semantic_golden_question_read_public" on semantic.golden_question for select using (is_active);
